apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: otomi-tekton-listener
  namespace: otomi-pipelines
spec:
  triggers:
    - name: otomi-tekton-listener
      bindings:
        - ref: otomi-tekton-binding
      template:
        ref: otomi-tekton-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: otomi-tekton-triggers-sa
            containers:
              - resources: #{ { - toYaml .Values.elResources | nindent 18 } } To be used by helm
                  requests:
                    memory: '64Mi'
                    cpu: '250m'
                  limits:
                    memory: '128Mi'
                    cpu: '500m'
