apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphite
  name: graphite
spec:
  ports:
  - name: transport
    port: 2003
    protocol: TCP
    targetPort: transport
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: graphite
