{{- $v := .Values.pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sitespeed-results
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: {{ $v.results }}
---      
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sitespeed-graphite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: {{ $v.graphite }}
