apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sitespeed-chrome
  labels:
    app: sitespeed
spec:
  schedule: {{ $v.schedule.sitespeed }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          name: sitespeed-chrome
          labels:
            app: sitespeed
        spec:
          containers:
            - image: sitespeedio/sitespeed.io:10.3.2
              name: sitespeed-chrome
              resources:
                requests:
                  cpu: 500m
                  memory: 512Mi
                limits:
                  cpu: 1
                  memory: 1Gi
              command: ["bash", "-c"]
              args:
                - |
                  start.sh \
                    -v --debug --graphite.host=graphite.monitoring \
                    {{- range $site := $v.sites }}
                    https://{{ $site }} \
                    {{- end }}
                    --multi
                    # targets.txt
                    # --browsertime.chrome.args='proxy-server=socks5://sitespeed-throttling-proxy:1080' \
              volumeMounts:
                - name: size-limit
                  mountPath: /dev/shm
                - name: sitespeed-results
                  mountPath: /sitespeed.io/sitespeed-result
                - name: gitdata
                  mountPath: /gitdata
          volumes:
            - name: size-limit
              emptyDir:
                sizeLimit: "1000Mi"
                medium: "Memory"
            - name: sitespeed-results
              persistentVolumeClaim:
                claimName: sitespeed-results
          restartPolicy: Never
