apiVersion: v1
data:
  kconfig.sh: "mkdir \"${HOME}/.kube\"\nKUBECONFIG=\"${HOME}/.kube/config\"\nTOKEN=\"$(cat
    /var/run/secrets/kubernetes.io/serviceaccount/token)\"\nCA_CRT=\"$(base64 -w 0
    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)\"\n\ncat <<EOF > \"${KUBECONFIG}\"\napiVersion:
    v1\nkind: Config\nclusters:\n- name: otomi \n  cluster:\n    certificate-authority-data:
    ${CA_CRT}\n    server: https://kubernetes.default.svc.cluster.local\ncontexts:\n-
    name: default-context\n  context:\n    cluster: otomi\n    namespace: default\n
    \   user: team-${TEAM}-user \ncurrent-context: default-context\nusers:\n- name: team-${TEAM}-user\n
    \ user:\n    token: ${TOKEN}\nEOF\n"
kind: ConfigMap
metadata:
  name: kconfig
  namespace: team-${TEAM}
---

