apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: team-${TEAM}-role
  namespace: team-${TEAM}
rules:
  - apiGroups:
      - ''
    resources:
      - '*'
    verbs:
      - '*'
---

