kind: pipeline
type: kubernetes
name: default

# metadata:
#   annotations:
#     sidecar.istio.io/inject: "false"

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    commands:
      - echo "Cloning ${DRONE_REPO} ..."
      - git clone https://github.com/${DRONE_REPO} .
      - git checkout $DRONE_COMMIT
      - sed -e "s/#CLOUD#/$${CLOUD}/g" -e "s/#CLUSTER#/$${CLUSTER}/g" .drone.yml > /tmp/.drone.yml && cat /tmp/.drone.yml > .drone.yml
      - cat .drone.yml
    when:
      event:
        - push
        - pull_request
        - tag

  - name: deploy-dev
    image: otomi/tools:1.1.4
    depends_on:
      - clone
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    commands:
      - cat .drone.yaml
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    depends_on:
      - deploy-dev
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: demo
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    depends_on:
      - deploy-demo
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: prd
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    when:
      ref: [refs/tags/v*]
      event:
        - tag

  - name: slack
    image: plugins/slack
    environment:
      CLUSTER: ${CLUSTER}
      CLOUD: ${CLOUD}
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: mon-otomi-#CLOUD#-#CLUSTER#
      username: Drone
      # template: >
      #   {{#success build.status}}
      #     Deployment to cluster '#CLOUD#-#CLUSTER#' succeeded.
      #   {{else}}
      #     Deployment to cluster '#CLOUD#-#CLUSTER#' failed. Please take a look.
      #   {{/success}}
    depends_on:
      - deploy-#CLUSTER#
    when:
      status:
        - success
        - failure

