kind: pipeline
type: kubernetes
name: default

metadata:
  annotations:
    sidecar.istio.io/inject: "false"

steps:
  - name: deploy-dev
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/deploy.sh
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/deploy.sh
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: demo
    depends_on:
      - deploy-dev
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/deploy.sh
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: prd
    depends_on:
      - deploy-demo
    when:
      ref: [refs/tags/v*]
      event:
        - tag
