kind: pipeline
type: docker
name: default

steps:
  - name: deploy-dev
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: dev
    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: demo
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: prd
    when:
      ref: [refs/tags/v*]
      event:
        - tag
