kind: pipeline
type: kubernetes
name: default

metadata:
  annotations:
    sidecar.istio.io/inject: "false"

steps:
  - name: deploy-dev
    image: otomi/tools:1.1.4
    command:
      - pwd && ls
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/deploy.sh
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}

    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    command:
      - ./tests/lint.sh
      - ./bin/deploy.sh
    environment:
      CLUSTER: demo
      CLOUD: ${CLOUD}
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    command:
      - ./tests/lint.sh
      - ./bin/deploy.sh
    environment:
      CLUSTER: prd
    when:
      ref: [refs/tags/v*]
      event:
        - tag
