kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: otomi/tools:1.1.4
    environment:
      CLUSTER: ${CLUSTER}
      CLOUD: ${CLOUD}
    commands:
      - /bin/bash ./tests/lint.sh
    when:
      event:
        - push
        - pull_request

  - name: deploy-dev
    image: otomi/tools:1.1.4
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    commands:
      - /bin/bash ./bin/sync.sh
    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    depends_on:
      - deploy-dev
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: demo
    commands:
      - /bin/bash ./bin/sync.sh
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    depends_on:
      - deploy-demo
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: prd
    commands:
      - /bin/bash ./bin/sync.sh
    when:
      ref: [refs/tags/v*]
      event:
        - tag

  - name: maintenance
    image: otomi/tools:1.1.4
    environment:
      CLUSTER: ${CLUSTER}
      CLOUD: ${CLOUD}
    commands:
      - echo "Killing istio-pilot pod..."
      - kubectl -n istio-system delete po $(kubectl -n istio-system get po -l "istio=pilot,app=pilot" -ojsonpath='{.items[0].metadata.name}')
    depends_on:
      - deploy-CCCLUSTER
    when:
      branch: master
      event:
        - push

  - name: slack
    image: plugins/slack
    environment:
      CLUSTER: ${CLUSTER}
      CLOUD: ${CLOUD}
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: mon-otomi-CCCLOUD-CCCLUSTER
      username: Drone
      template: >
        {{#success build.status}}
          Completed syncing cluster 'CCCLOUD-CCCLUSTER' :)
        {{else}}
          Failed syncing cluster 'CCCLOUD-CCCLUSTER' ;( Please take a look.
        {{/success}}
    depends_on:
      - deploy-CCCLUSTER
    when:
      status:
        - success
        - failure
