kind: pipeline
type: kubernetes
name: default

metadata:
  annotations:
    sidecar.istio.io/inject: "false"

steps:
  - name: test
    image: otomi/tools:1.1.4
    command:
      - ./tests/lint.sh
    environment:
      STAGE: dev
      CLOUD: ${CLOUD}
    when:
      event:
        - push
        - pull_request

  - name: deploy-dev
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: dev
      CLOUD: ${CLOUD}
    depends_on:
      - test

    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: demo
      CLOUD: ${CLOUD}
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    command:
      - ./bin/deploy.sh
    environment:
      STAGE: prd
    when:
      ref: [refs/tags/v*]
      event:
        - tag
