kind: pipeline
type: kubernetes
name: default

# metadata:
#   annotations:
#     sidecar.istio.io/inject: "false"

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    commands:
      - echo "Cloning..."
      - git clone $DRONE_REPO .
      - git checkout $DRONE_COMMIT
      - sed -e "s/#CLOUD#/${CLOUD}/g" -e "s/#CLUSTER#/${CLUSTER}/g" .drone.yml > /tmp/.drone.yml && cat /tmp/.drone.yml > .drone.yml

steps:
  - name: deploy-dev
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    environment:
      CLUSTER: dev
      CLOUD: ${CLOUD}
    when:
      event:
        - push
        - pull_request

  - name: deploy-demo
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: demo
    depends_on:
      - deploy-dev
    when:
      ref: [refs/tags/v*-DEMO]
      event:
        - tag

  - name: deploy-prd
    image: otomi/tools:1.1.4
    commands:
      - /bin/bash ./tests/lint.sh
      - /bin/bash ./bin/sync.sh
    environment:
      CLOUD: ${CLOUD}
      CLUSTER: prd
    depends_on:
      - deploy-demo
    when:
      ref: [refs/tags/v*]
      event:
        - tag

  - name: slack
    image: plugins/slack
    environment:
      CLUSTER: ${CLUSTER}
      CLOUD: ${CLOUD}
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: mon-otomi-#CLOUD#-#CLUSTER#
      username: Drone
      template: >
        {{#success build.status}}
          Deployment to cluster '#CLOUD#-#CLUSTER#' succeeded.
        {{else}}
          Deployment to cluster '#CLOUD#-#CLUSTER#' failed. Please take a look.
        {{/success}}
    depends_on:
      - deploy-#CLUSTER#
    when:
      status:
        - success
        - failure

