stages:
  - test
  - deploy

test:
  image: otomi/tools:1.0.1
  stage: test
  script:
    - sh ./tests/lint.sh

deploy-dev:
  image: otomi/tools:1.0.1
  stage: deploy
  environment:
    name: dev
  variables:
    KUBE_TOKEN: ${KUBE_TOKEN_DEV}
  script:
    - ./bin/deploy.sh
  only:
    - master

deploy-tst:
  image: otomi/tools:1.0.1
  stage: deploy
  environment:
    name: tst
  variables:
    KUBE_TOKEN: ${KUBE_TOKEN_TST}
  script:
    - ./bin/deploy.sh
  only:
    - master
  when: manual

deploy-acc:
  image: otomi/tools:1.0.1
  stage: deploy
  environment:
    name: acc
  variables:
    KUBE_TOKEN: ${KUBE_TOKEN_ACC}
  script:
    - ./bin/deploy.sh
  only:
    - master
  when: manual

deploy-prd:
  image: otomi/tools:1.0.1
  stage: deploy
  environment:
    name: prd
  variables:
    KUBE_TOKEN: ${KUBE_TOKEN_PRD}
  script:
    - ./bin/deploy.sh
  only:
    - master
  when: manual
