apiVersion: v1
kind: ServiceAccount
metadata:
  name: otomi-tekton-triggers-sa
  namespace: otomi-pipelines
  # {{- with .Values.serviceAccount.annotations }}  # To be used by helm
  # annotations:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otomi-tekton-tasks-sa
  namespace: otomi-pipelines
