apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-2"
  name: otomi-tekton-binding
  namespace: otomi-pipelines
spec:
  params:
    - name: repoUrl
      value: $(body.repository.clone_url)
    - name: commitMessage
      value: $(body.head_commit.message)
