---
apiVersion: "security.cloud.ibm.com/v1"
kind: Policy
metadata:
  name: sample-app-policy
  namespace: sample-app
  labels:
    app: sample-app
spec:
  targets:
    -
      # serviceName - the name of Kubernetes service in the Policy namespace that you want to protect.
      serviceName: svc-sample-app
      paths: 
        - prefix: /
          # method - ALL, GET, PUT, POST, DELETE, PATCH - Defaults to ALL
          method: ALL
          policies:
            - policyType: oidc
              config: oidc-provider-config-with-secret-ref
              # After successful authentication client is redirected  the original request URL. You may enforce a specific URL by setting redirectUri
              