isManaged: true
hasCloudLB: false
publicIngressClass: nginx
emailDomain: redkubes.com
sites: []
sitespeed: []

customerLabels:
  customer: redkubes

cert-manager:
  stage: "staging"
  emailUser: admins # @ domain will be appended

drone:
  server:
    adminUser: Morriz
  sourceControl:
    github:
      clientID: 6455ffb30c8e270c402f
      clientSecretValue: 7263c100c2b93064348fe4208c9b3da1bb0787db

index:
  image:
    tag: 1.0.5
    pullPolicy: Always

istio:
  gateway:
    name: otomi
    namespace: ingress
  profile: sds
  sds:
    enabled: true
  mtls:
    enabled: false

oauth2-proxy:
  config:
    cookieSecret: QkVwdy9MSkU0N3VYS2haZkVqZTdyUzExeFZheTM3YXk=

oidc:
  provider: azure
  scope: "openid email groups"

  # GitHub
  # provider: github
  # clientID: 5ee6373eec36e3616f8a
  # clientSecret: 153acea33adb0d6fccb7e4e757d24b53d439215c
  # Azure
  # provider: azure
  clientID: 5eb129f2-1b26-4910-a05a-70d8b6a380cd
  clientSecret: 3F]Eho:Nwo96e7RPQxDBBYdHHxeE:Tp=

  microsoft:
    # v2, for dex:
    issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/v2.0
    tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
  azure:
    # v1, for oauth2-proxy:
    issuer: https://sts.windows.net/57a3f6ea-7e70-4260-acb4-e06ce452f695/
    # issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/v2.0
    tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
  google:
    issuer: https://accounts.google.com
  github:
    org: redkubes

prometheus-operator:
  alertmanager:
    slackUrl: https://hooks.slack.com/services/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
    channelGroup: otomi
    groupInterval: 5m
    repeatInterval: 3h
