isManaged: true
isMultitenant: true
ingress:
  allowedCidrs: []
hasCloudLB: false
useCloudCA: false
emailDomain: redkubes.com
sites: []

customerLabels:
  customer: redkubes

oidc:
  provider: azure
  scope: "openid email groups"

  # GitHub
  # provider: github
  # clientID: 5ee6373eec36e3616f8a
  # clientSecret: 153acea33adb0d6fccb7e4e757d24b53d439215c
  # Azure
  # provider: azure
  clientID: 5eb129f2-1b26-4910-a05a-70d8b6a380cd
  clientSecret: "s-l0W.=WFx=8zAfcAKdbLBWj6NTXKDD0"
  authUrl: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/oauth2/authorize
  tokenUrl: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/oauth2/token

  azure:
    # v1, for oauth2-proxy:
    issuer: https://sts.windows.net/57a3f6ea-7e70-4260-acb4-e06ce452f695/
    # issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/v2.0
    tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
  google:
    issuer: https://accounts.google.com
  github:
    org: redkubes

charts:
  cert-manager:
    stage: "staging" # production
    emailUser: admins # @ domain will be appended

  drone:
    orgs: redkubes
    server:
      adminUser: Morriz

  index:
    isNS: true
    image:
      tag: 1.0.5-ns

  istio:
    gateway:
      name: otomi
      namespace: ingress
    profile: sds
    sds:
      enabled: true
    mtls:
      enabled: false

  loki:
    adminPassword: adminnns
    storageType: filesystem
    retention:
      duration: 6h
      period: 24h
    persistence:
      size: 20Gi

  oauth2-proxy:
    config:
      cookieSecret: QkVwdy9MSkU0N3VYS2haZkVqZTdyUzExeFZheTM3YXk=

  prometheus-operator:
    alertmanager:
      slackUrl: https://hooks.slack.com/services/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
      channelGroup: otomi
      groupInterval: 5m
      repeatInterval: 3h
    grafana:
      adminPassword: bladibla

  sitespeed:
    retention: "10m:7d,30m:14d"
    schedule: "*/30 * * * *"
    pvc:
      results: 10Gi
      graphite: 2Gi
