isManaged: true
isMultitenant: true
ingress:
  allowedCidrs: []
hasCloudLB: false
useCloudCA: false
emailDomain: redkubes.com
sites: []

customerLabels:
  customer: redkubes

secret:
  gcr:
    description: Credentials for acessing otomi Google Container Registry (a.k.a imagePullSecrets)
    secretName: gcr-json-key
    data: eyJhdXRocyI6eyJodHRwczovL2V1Lmdjci5pbyI6eyJ1c2VybmFtZSI6Il9qc29uX2tleSIsInBhc3N3b3JkIjoie1xuICBcInR5cGVcIjogXCJzZXJ2aWNlX2FjY291bnRcIixcbiAgXCJwcm9qZWN0X2lkXCI6IFwiazhzLXBsYXlncm91bmQtMjU2MTEzXCIsXG4gIFwicHJpdmF0ZV9rZXlfaWRcIjogXCI2M2ZmM2FjNDU5NjgwZDI4N2RjZWVkYmFiNWFlZjljMTQwYzU2OWE1XCIsXG4gIFwicHJpdmF0ZV9rZXlcIjogXCItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURRU29XZllXb3A4bVlxXFxucG1UNU9HZTMwaURzQnBaYlRuV04xYXNpdDFreHQ1YkozZUhJeTRpdW5DRHhPeWJMRkVmMXNSN2JKRmtuNnZvQ1xcbmFsS3pHODVIeEs3c21tQ2ttVWJramhSNSthcjYwS2JVRi8wWFdrekk3SHlGY214N1EreW9laTRJaGs5QS9zcGJcXG53VHJya1RSYkt5UjRFUkxMOWRhdGhublZSdmgxT1ZkQzM4RVFNSHp6ZkRZUldDak1QTDY1aWc2TlhzNTNoZktMXFxucDlWOGh4OFlQZHBTT1luSnpWRTRHdkZ6UUthV0xqWWpxSWVaaVlVZmZ5Vy9qRzNCMEIyczNtdjVuditoRVN1YVxcbjArNjVqMVN4aVAvSXd4cktyOEIxUlpHbVVrSGpJWGJ5NVY4Q1VkVU1Yd3NjMWpNblU0Mmh6L1VFOXRPRm1qc0pcXG5sL3VvWXFOYkFnTUJBQUVDZ2dFQVVRMTJ3dWNXOTF5K3VnRUhFTjRNcWtEb0U4Q2FlTXhtdlRzMHZhMG9WY3J4XFxuci9zYU5kZFNDRlIwRXpzbjVPV3UvT0lnTmptR1FoelRqZVlPNldpOEZEeHFyMktCa2Z1ZFZTb2V1THBaZVFHQlxcbnNjM2w3RlQweFVrVlNaNlZyVC9vMDBTOExoQUp2aXFIMXoyeHJtSlNROW5kZHFWNk1Za29NVjAvZ3FsNzNLMHdcXG5HS2NtaWZyalM0UGRjTXdvZWFJM05KZHlmVTU1R3FMVHFraDJtaUZDWlFXV01sOWlEc0dqdDhZN2pXWVJxZ2JOXFxuVnBYc1dFdGpWYTZ5WURRb0dvbkwxWjZxTHMzcW14RGZrUHdQTGJPSVBkclB4NGZQU3FtY1RFWmNld3VieUJhNVxcbjhOM1h6QnRzWVJDTllORzZ5K01rd05IUk5JRU8vYi9JcTBBalJiYVgwUUtCZ1FEem9aZ2J4ODB0WE9xSm40aUpcXG5PZ2lwV3VtZWJaS2NmTjF0ZVZRanVBT0tQQm9CSVNTNGtIdnZUSjZMOWVxSFllTXloMVUwQ01DUWtTVlREdFNwXFxuYzg0NmJqczBvVnlNekQ3Q0hwcmMyMDloV05Cb0dsS3lyZFNXQlQ5ZVplSDF2TGJMQllNNTRnSGVaWWI2d3hJcVxcbmxjejc3c0tEZjlnTDFGTHg2RFIyV1YyZDBRS0JnUURhM1o5Sm1pOXBGTXNOZG1NeFVESDAvUDBDZm4rcUpwWVdcXG5Ld2psU3Y0WHhBTnBwYld2aDNmMFpNSWZyV25PWlVLRjZ3WEpiQmtSc2tNbjlnZ1FoeStuTzJGU2U4SS9CakgyXFxuODFDMEExcWdzL1Azb044Y0x3NXhBelZNQ1h2RWs2WEtuUHY5UTlDNzZ3eW81ZDVHK3VDa0NpWUZsS2dpR28vS1xcbjZoUjlVSkVkYXdLQmdRQ2dFOXd5M0t3bWt6ZVRwNXY1dG9UOGFieTRtUHhORUFvWnBTK3dySGErL0ZDRnozWW1cXG5RdUQ3MGRjVzFVVDlJVWM3NndvRHY0QnZQTDlPZko4a20rKzBHcnVTRURnVVZ4c2hSeVN2MnZXa1c4dkxxd2dOXFxuV1FRbWNsbzV0eTJwM2c0cEJYMDhxaEJhUlZGVU1Kb2VHd0Z0dzJwUkpzNFlyN0MwTzhORXcrRXNFUUtCZ0JwM1xcblZFeTlOV0I2b0RkSGlxVXE4bStTckRIQ0JFUWFHR29qMkJhS0pBSFJ0U3Z3V3ZFWDY1eUZGcWhuK3ZSM2NEenJcXG5kNjZzd0xkUUhDalg2bys5R1RrYXlDRUdVQzM0M00vbENteEtQNHBSV0g0b1dQSjZpaitHU01xaUZ2SmxmRlhzXFxuOTlmZmZIMU01aUlDY2dlWlROTHBXMEd2Z1VsbWR0N3R3WDZKNEpKekFvR0JBTm0rRlJ2TFg3VklhRVA4UHUzZVxcbkxOWmlYZlJxZW80SjVZTDZUR0tjMW5iZHJHdElOUWl2alZNdHZFTFo2cTl1N0ViVjdPSTBGQ3I3dDlsejZIOG5cXG5xU1g3ait4eDBMYjk2OHRoTzhaRUQzcFFJRXN3UUNvNTlveUk0akxzK0xIS2ROZzRjenZGbGI1bU1xbTcyQXNTXFxuTktBVnM5eFVSQUlxUjFmUHYvZG9mVExZXFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxcblwiLFxuICBcImNsaWVudF9lbWFpbFwiOiBcImdjci1hdXRoLXJvQGs4cy1wbGF5Z3JvdW5kLTI1NjExMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbVwiLFxuICBcImNsaWVudF9pZFwiOiBcIjExNDU0MjM5OTY5ODg0OTM4MjA1NVwiLFxuICBcImF1dGhfdXJpXCI6IFwiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGhcIixcbiAgXCJ0b2tlbl91cmlcIjogXCJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlblwiLFxuICBcImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybFwiOiBcImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0c1wiLFxuICBcImNsaWVudF94NTA5X2NlcnRfdXJsXCI6IFwiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9nY3ItYXV0aC1ybyU0MGs4cy1wbGF5Z3JvdW5kLTI1NjExMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbVwiXG59IiwiZW1haWwiOiJnY3ItYXV0aC1yb0BrOHMtcGxheWdyb3VuZC0yNTYxMTMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdXRoIjoiWDJwemIyNWZhMlY1T25zS0lDQWlkSGx3WlNJNklDSnpaWEoyYVdObFgyRmpZMjkxYm5RaUxBb2dJQ0p3Y205cVpXTjBYMmxrSWpvZ0ltczRjeTF3YkdGNVozSnZkVzVrTFRJMU5qRXhNeUlzQ2lBZ0luQnlhWFpoZEdWZmEyVjVYMmxrSWpvZ0lqWXpabVl6WVdNME5UazJPREJrTWpnM1pHTmxaV1JpWVdJMVlXVm1PV014TkRCak5UWTVZVFVpTEFvZ0lDSndjbWwyWVhSbFgydGxlU0k2SUNJdExTMHRMVUpGUjBsT0lGQlNTVlpCVkVVZ1MwVlpMUzB0TFMxY2JrMUpTVVYyWjBsQ1FVUkJUa0puYTNGb2EybEhPWGN3UWtGUlJVWkJRVk5EUWt0bmQyZG5VMnRCWjBWQlFXOUpRa0ZSUkZGVGIxZG1XVmR2Y0RodFdYRmNibkJ0VkRWUFIyVXpNR2xFYzBKd1dtSlVibGRPTVdGemFYUXhhM2gwTldKS00yVklTWGswYVhWdVEwUjRUM2xpVEVaRlpqRnpVamRpU2tacmJqWjJiME5jYm1Gc1MzcEhPRFZJZUVzM2MyMXRRMnR0VldKcmFtaFNOU3RoY2pZd1MySlZSaTh3V0ZkcmVrazNTSGxHWTIxNE4xRXJlVzlsYVRSSmFHczVRUzl6Y0dKY2JuZFVjbkpyVkZKaVMzbFNORVZTVEV3NVpHRjBhRzV1VmxKMmFERlBWbVJETXpoRlVVMUllbnBtUkZsU1YwTnFUVkJNTmpWcFp6Wk9XSE0xTTJobVMweGNibkE1Vmpob2VEaFpVR1J3VTA5WmJrcDZWa1UwUjNaR2VsRkxZVmRNYWxscWNVbGxXbWxaVldabWVWY3Zha2N6UWpCQ01uTXpiWFkxYm5ZcmFFVlRkV0ZjYmpBck5qVnFNVk40YVZBdlNYZDRja3R5T0VJeFVscEhiVlZyU0dwSldHSjVOVlk0UTFWa1ZVMVlkM05qTVdwTmJsVTBNbWg2TDFWRk9YUlBSbTFxYzBwY2Jtd3ZkVzlaY1U1aVFXZE5Ra0ZCUlVOblowVkJWVkV4TW5kMVkxYzVNWGtyZFdkRlNFVk9ORTF4YTBSdlJUaERZV1ZOZUcxMlZITXdkbUV3YjFaamNuaGNibkl2YzJGT1pHUlRRMFpTTUVWNmMyNDFUMWQxTDA5SlowNXFiVWRSYUhwVWFtVlpUelpYYVRoR1JIaHhjakpMUW10bWRXUldVMjlsZFV4d1dtVlJSMEpjYm5Oak0ydzNSbFF3ZUZWclZsTmFObFp5VkM5dk1EQlRPRXhvUVVwMmFYRklNWG95ZUhKdFNsTlJPVzVrWkhGV05rMVphMjlOVmpBdlozRnNOek5MTUhkY2JrZExZMjFwWm5KcVV6UlFaR05OZDI5bFlVa3pUa3BrZVdaVk5UVkhjVXhVY1d0b01tMXBSa05hVVZkWFRXdzVhVVJ6UjJwME9GazNhbGRaVW5GbllrNWNibFp3V0hOWFJYUnFWbUUyZVZsRVVXOUhiMjVNTVZvMmNVeHpNM0Z0ZUVSbWExQjNVRXhpVDBsUVpISlFlRFJtVUZOeGJXTlVSVnBqWlhkMVlubENZVFZjYmpoT00xaDZRblJ6V1ZKRFRsbE9Selo1SzAxcmQwNUlVazVKUlU4dllpOUpjVEJCYWxKaVlWZ3dVVXRDWjFGRWVtOWFaMko0T0RCMFdFOXhTbTQwYVVwY2JrOW5hWEJYZFcxbFlscExZMlpPTVhSbFZsRnFkVUZQUzFCQ2IwSkpVMU0wYTBoMmRsUktOa3c1WlhGSVdXVk5lV2d4VlRCRFRVTlJhMU5XVkVSMFUzQmNibU00TkRaaWFuTXdiMVo1VFhwRU4wTkljSEpqTWpBNWFGZE9RbTlIYkV0NWNtUlRWMEpVT1dWYVpVZ3hka3hpVEVKWlRUVTBaMGhsV2xsaU5uZDRTWEZjYm14amVqYzNjMHRFWmpsblRERkdUSGcyUkZJeVYxWXlaREJSUzBKblVVUmhNMW81U20xcE9YQkdUWE5PWkcxTmVGVkVTREF2VURCRFptNHJjVXB3V1ZkY2JrdDNhbXhUZGpSWWVFRk9jSEJpVjNab00yWXdXazFKWm5KWGJrOWFWVXRHTm5kWVNtSkNhMUp6YTAxdU9XZG5VV2g1SzI1UE1rWlRaVGhKTDBKcVNESmNiamd4UXpCQk1YRm5jeTlRTTI5T09HTk1kelY0UVhwV1RVTllka1ZyTmxoTGJsQjJPVkU1UXpjMmQzbHZOV1ExUnl0MVEydERhVmxHYkV0bmFVZHZMMHRjYmpab1VqbFZTa1ZrWVhkTFFtZFJRMmRGT1hkNU0wdDNiV3Q2WlZSd05YWTFkRzlVT0dGaWVUUnRVSGhPUlVGdlduQlRLM2R5U0dFckwwWkRSbm96V1cxY2JsRjFSRGN3WkdOWE1WVlVPVWxWWXpjMmQyOUVkalJDZGxCTU9VOW1TamhyYlNzck1FZHlkVk5GUkdkVlZuaHphRko1VTNZeWRsZHJWemgyVEhGM1owNWNibGRSVVcxamJHODFkSGt5Y0RObk5IQkNXREE0Y1doQ1lWSldSbFZOU205bFIzZEdkSGN5Y0ZKS2N6UlpjamRETUU4NFRrVjNLMFZ6UlZGTFFtZENjRE5jYmxaRmVUbE9WMEkyYjBSa1NHbHhWWEU0YlN0VGNrUklRMEpGVVdGSFIyOXFNa0poUzBwQlNGSjBVM1ozVjNaRldEWTFlVVpHY1dodUszWlNNMk5FZW5KY2JtUTJObk4zVEdSUlNFTnFXRFp2S3psSFZHdGhlVU5GUjFWRE16UXpUUzlzUTIxNFMxQTBjRkpYU0RSdlYxQktObWxxSzBkVFRYRnBSblpLYkdaR1dITmNiams1Wm1abVNERk5OV2xKUTJOblpWcFVUa3h3VnpCSGRtZFZiRzFrZERkMGQxZzJTalJLU25wQmIwZENRVTV0SzBaU2RreFlOMVpKWVVWUU9GQjFNMlZjYmt4T1dtbFlabEp4Wlc4MFNqVlpURFpVUjB0ak1XNWlaSEpIZEVsT1VXbDJhbFpOZEhaRlRGbzJjVGwxTjBWaVZqZFBTVEJHUTNJM2REbHNlalpJT0c1Y2JuRlRXRGRxSzNoNE1FeGlPVFk0ZEdoUE9GcEZSRE53VVVsRmMzZFJRMjgxT1c5NVNUUnFUSE1yVEVoTFpFNW5OR042ZGtac1lqVnRUWEZ0TnpKQmMxTmNiazVMUVZaek9YaFZVa0ZKY1ZJeFpsQjJMMlJ2WmxSTVdWeHVMUzB0TFMxRlRrUWdVRkpKVmtGVVJTQkxSVmt0TFMwdExWeHVJaXdLSUNBaVkyeHBaVzUwWDJWdFlXbHNJam9nSW1kamNpMWhkWFJvTFhKdlFHczRjeTF3YkdGNVozSnZkVzVrTFRJMU5qRXhNeTVwWVcwdVozTmxjblpwWTJWaFkyTnZkVzUwTG1OdmJTSXNDaUFnSW1Oc2FXVnVkRjlwWkNJNklDSXhNVFExTkRJek9UazJPVGc0TkRrek9ESXdOVFVpTEFvZ0lDSmhkWFJvWDNWeWFTSTZJQ0pvZEhSd2N6b3ZMMkZqWTI5MWJuUnpMbWR2YjJkc1pTNWpiMjB2Ynk5dllYVjBhREl2WVhWMGFDSXNDaUFnSW5SdmEyVnVYM1Z5YVNJNklDSm9kSFJ3Y3pvdkwyOWhkWFJvTWk1bmIyOW5iR1ZoY0dsekxtTnZiUzkwYjJ0bGJpSXNDaUFnSW1GMWRHaGZjSEp2ZG1sa1pYSmZlRFV3T1Y5alpYSjBYM1Z5YkNJNklDSm9kSFJ3Y3pvdkwzZDNkeTVuYjI5bmJHVmhjR2x6TG1OdmJTOXZZWFYwYURJdmRqRXZZMlZ5ZEhNaUxBb2dJQ0pqYkdsbGJuUmZlRFV3T1Y5alpYSjBYM1Z5YkNJNklDSm9kSFJ3Y3pvdkwzZDNkeTVuYjI5bmJHVmhjR2x6TG1OdmJTOXliMkp2ZEM5Mk1TOXRaWFJoWkdGMFlTOTROVEE1TDJkamNpMWhkWFJvTFhKdkpUUXdhemh6TFhCc1lYbG5jbTkxYm1RdE1qVTJNVEV6TG1saGJTNW5jMlZ5ZG1salpXRmpZMjkxYm5RdVkyOXRJZ3A5In19fQ==

otomiStackApi:
  git:
    localPath: /tmp/otomi-stack
    repoUrl: github.com/j-zimnowoda/test.git
    user: test63688
    email: test63688@gmail.com
    password: wUnkus-cakzow-3nirky

oidc:
  provider: azure
  scope: "openid email groups"

  # GitHub
  # provider: github
  # clientID: 5ee6373eec36e3616f8a
  # clientSecret: 153acea33adb0d6fccb7e4e757d24b53d439215c
  # Azure
  # provider: azure
  clientID: 5eb129f2-1b26-4910-a05a-70d8b6a380cd
  clientSecret: "s-l0W.=WFx=8zAfcAKdbLBWj6NTXKDD0"
  authUrl: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/oauth2/authorize
  tokenUrl: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/oauth2/token

  azure:
    # v1, for oauth2-proxy:
    issuer: https://sts.windows.net/57a3f6ea-7e70-4260-acb4-e06ce452f695/
    # issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/v2.0
    tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
  google:
    issuer: https://accounts.google.com
  github:
    org: redkubes

charts:
  cert-manager:
    stage: "staging" # production
    emailUser: admins # @ domain will be appended

  drone:
    orgs: redkubes
    server:
      adminUser: Morriz

  index:
    isNS: true
    image:
      tag: 1.0.5-ns

  istio:
    gateway:
      name: otomi
      namespace: ingress
    profile: sds
    sds:
      enabled: true
    mtls:
      enabled: false

  loki:
    adminPassword: adminnns
    storageType: filesystem
    retention:
      duration: 6h
      period: 24h
    persistence:
      size: 20Gi

  oauth2-proxy:
    config:
      cookieSecret: QkVwdy9MSkU0N3VYS2haZkVqZTdyUzExeFZheTM3YXk=

  prometheus-operator:
    alertmanager:
      slackUrl: https://hooks.slack.com/services/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
      channelGroup: otomi
      groupInterval: 5m
      repeatInterval: 3h
    grafana:
      adminPassword: bladibla

  sitespeed:
    retention: "10m:7d,30m:14d"
    schedule: "*/30 * * * *"
    pvc:
      results: 10Gi
      graphite: 2Gi
  otomi:
    imagePullSecrets:
    - name:  gcr-json-key