sites:
# - otomi.cloud

sitespeed:
  # - host: otomi.cloud
  #   paths: [/]

google:
  projectId: otomi-cloud
  cloudDnsKey: |
    {
      "type": "service_account",
      "project_id": "otomi-cloud",
      "private_key_id": "abeae4d84ea7fda02c29bb9fdd0705625b1e4122",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4Ciuzqi++09do\nd3YC8jUuOPjoYr4ztkr5gwFOztqles21iSF8Vv3GTJ02KSQcoyVKBtLnwudsuMmT\nW8+Ec4bivWzAWy97oZZBWJe0TfGmaBM9nx4mkohVJkwbG+FUSk8Mr0csfRJLbKGN\n08vM+5S35pLMh2E1suyTYxACT0P2M3eR8y1IaXWdXkIJFk8Sgj0xDcbO5heKfKtY\nQR5A5EcTVTu20Dkcgb2DUOgl+5+N7TIDXcHV4j4LSjj104E6Fn0GYY+tswlpew4m\nG9y3zjILy6BcuDSz5MsEIK7POMOlX3f6P7gq7Y6pkrgdv3LMbMoNGaZ7xFJx0BCh\n5JJgv5u3AgMBAAECggEAR+NVKcN3DfvSvxA2zTTOGCWR+LglYq64v5jwKFf9qTj8\nZIZRya9zRoPDvxW38OW7WZyrwnLsEhhmSMTKnQrBbA0hD0wvEoROXG0eKQRvOZia\nt23RibCgR16DyO0Nie7SzPoke5jJTiP7QRqzl3jIIUOUIQdare6boYDHDpfmzKKp\nSgJMjx46pw4IiQ9h1iCBvT21nII/CJtfo2/goDAzlypARXpzDeEt2OesohauK0Cy\nM7fTAuvIlW0YsEpfGFla+5OqHXYNC/CPHteZ4Wu2xFXDmfa77g1d6vfxOrO7Ly7a\nq6SGq/lvCCh30vrRHuDkptuwXaS42ZmtX7EE4QprPQKBgQDg+YafEzOwuGe9lorc\nH11YMOnTJ5mXsynPnAdgCjL06YC9NJQSfj1RibKrGkQr6uXTVY9Me4zRqK4/GYKU\nNKj7EsKq2N57YLrrvWE/79mVlQa4vA9jiW1u1GJaHPtJPM8QCar+z7budm9Q2Hqj\nsi46ax6x05QReWEZ9NEHaeltVQKBgQDRa3t3EXdpplcCI5Lx+OA0XBAQF4W+vSJT\nLzpHBAImVXj1QPYjn/hQIjlEH48Rft6TEiDQDqOmXT4MTA7FTZ/qUHnceZY7yFz7\nW/yKntlIpZWzEwNo7lUFDStQ5Q0xf3WKvZAgNVObNXA3D2a9GF/L4aNcmw6u5jzi\nAxGv5PLE2wKBgAXEX78ULu8IyyABC+44n5vzJQtUqItK/Hdl+IptuICuu64d+u2+\nbrP4Y6wfMEAv9VRFjTbYs/Nr74uOi9pgvzQwdu0KQinHgQMqB6Qr8dfzyghSSdKz\nYyrEJwFIXOiztlsi5E9D49yZDKF16y7nEmhM9qx4UANiqSqRLAqUnHdBAoGAa5cy\n2Vtp5CeHcBvitNpOJdhekEXlerck2WPcJvwSNquW9zmmu2rGYjUTAsLL+AscQqb/\noKTEwwYIiLzSod9dlz49PV5iJtirnKAHwRgXPdGEdXoBOHmpyGyZonfrLVD0jJET\naNi82XK88izBdcj9/nswOLWY95ZmFR/KiHmxmB0CgYBJbEpsxhz1Q9I6NznKPRfQ\n2a/pcu1t+qZAqj0eHrwRRBa+blGBdQOrZoL5V4ATchMFFiwz02Bem0HLWG0BM+TW\nsM+OiehNNr98I9dTEX0Eih1V6RG7ijkGs/Cl+BHOyrffvkayG6X+ii8KIx/agRqb\nGpKBS8+aXX6AjjgxTf1AMQ==\n-----END PRIVATE KEY-----\n",
      "client_email": "dnsmanager@otomi-cloud.iam.gserviceaccount.com",
      "client_id": "110280203946287268503",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/dnsmanager%40otomi-cloud.iam.gserviceaccount.com"
    }

cloudDns:
  domain: otomi.cloud
  zone: otomi

cert-manager:
  provider:
    google:
      clouddns:
        project: otomi-cloud
        serviceAccountSecretRef:
          name: cloud-dns-key
          key: key.json

drone:
  sourceControl:
    github:
      clientID: 6455ffb30c8e270c402f
      clientSecretValue: 7263c100c2b93064348fe4208c9b3da1bb0787db

ingress-azure:
  appgw:
    subscriptionId: 50c24abd-f872-4a3b-9f65-419800dda5eb
    resourceGroup: k8s-redkubes-dev
    name: appgw-k8s-redkubes-dev
    usePrivateIP: false
    subnetName: appgw-subnet
    subnetPrefix: 10.1.0.0/16

istio:
  mtls:
    enabled: false
