{{- if and .Values.prometheus.enabled .Values.prometheus.additionalServiceMonitors }}
{{- range .Values.prometheus.additionalServiceMonitors }}
apiVersion: {{ printf "%s/v1" ($.Values.prometheusOperator.crdApiGroup | default "monitoring.coreos.com") }}
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  labels:
    app: {{ template "prometheus-operator.name" $ }}-prometheus
{{ include "prometheus-operator.labels" $ | indent 4 }}
    {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
{{ toYaml .endpoints | indent 4 }}
    {{- if $.Values.global.istioEnabled }}
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
        certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
        keyFile: /etc/prometheus/secrets/istio.default/key.pem
        insecureSkipVerify: true
    {{- end }}
  {{- if .jobLabel }}
  jobLabel: {{ .jobLabel }}
  {{- end }}
  {{- if .namespaceSelector }}
  namespaceSelector:
{{ toYaml .namespaceSelector | indent 4 }}
  {{- end }}
  selector:
{{ toYaml .selector | indent 4 }}
  {{- if .targetLabels }}
  targetLabels:
{{ toYaml .targetLabels | indent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
