bases:
  - ../snippets/defaults.yaml

environments:
  default:
    values:
      - ../../values/_env/default.yaml
      - ../../values/_customers/customers.yaml

---
{{- $v := .Environment.Values }}
{{- $custId := (requiredEnv "CUST_ID") }}
{{- $customers := $v.customers }}
{{ $cust := index $customers $custId }}
helmfiles:
  {{/* range $custId, $cust := $customers */}}
  {{- range $nsId, $ns := $cust.namespaces }}
  {{- $custNs := printf "cust-%s-%s" $custId $ns.name }}
  {{- if $cust.active }}
  - path: "../snippets/releases.gotmpl"
    values:
      - release:
          name: {{ $custNs }}
          namespace: {{ $custNs }}
          chart: customer-ns
          nameOverride: {{ $custNs }}
        {{- $cust.values | toYaml | nindent 8 }}
        isCustomer: true
        customerLabels:
          customer: {{ $custId }}
          namespace: {{ $ns.name }}
  {{- range $chart := $ns.charts }}
  - path: "../snippets/releases.gotmpl"
    values:
      - release:
          name: {{ $chart.name }}-{{ $custNs }}
          namespace: {{ $custNs }}
          chart: {{ $chart.name }}
        namespace: {{ $custNs }}
      - level: environment
        {{- $v | toYaml | nindent 8 }}
      - level: customer
        {{- $cust.values | toYaml | nindent 8 }}
        isCustomer: true
        customerLabels:
          customer: {{ $custId }}
          namespace: {{ $ns.name }}
      - level: chart
        {{- if $chart.values }}
        {{ $chart.name }}:
          {{ $chart.values | toYaml | nindent 10 }}
        {{- end }}
        {{- if not (hasKey $chart.values "domain") }}
        domain: {{ $cust.values | getOrNil "domain" | default (printf "%s.%s.%s" $ns.name $custId $v.customerDomain)}}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{/*- end */}}
  
# no main release here, as we abuse the above (sub)helmfiles to enable to inject namespace data