charts:
    otomi-api:
        git:
            localPath: /tmp/otomi-stack
            repoUrl: github.com/redkubes/otomi-values-demo.git
        image:
            pullPolicy: Always
            tag: latest
        tools:
            image:
                tag: latest
                pullPolicy: Always
