cluster:
  hasCloudLB: true

azure:
  tenantId: 64458159-0d9a-4d84-966f-1a13c0ac7a34
  subscriptionId: 2e69a31a-6cef-4493-b895-3a0d8e16e58e
  resourceGroup: AKS20-sandbox
  diskType: Standard_LRS # Premium_LRS
  clientId: 4795daf6-f95f-4170-8b75-f58396550ddc
  clientSecret: Ss[KSDDDYtoOz/_DaT:wDSUZK3vV4E59

charts:
  cert-manager:
    azureClientSecret: 3b4d0dc8-7342-4709-b1b0-fd70921dab48
    provider:
      azure:
        azuredns:
          clientID: 3909ceec-7ea0-46f8-b602-96886b876417
          clientSecretSecretRef:
            name: cert-manager-sp
            key: CLIENT_SECRET
          tenantID: 64458159-0d9a-4d84-966f-1a13c0ac7a34
          subscriptionID: 2e69a31a-6cef-4493-b895-3a0d8e16e58e
          resourceGroupName: dev-aks-dns
          hostedZoneName: aks.sandbox.cla.ns.nl

  cluster-autoscaler:
    image:
      tag: v1.16.3
    autoscalingGroups:
      - name: agentpool1
        minSize: 3
        maxSize: 7

  drone:
    sourceControl:
      github:
        clientID: eb64c85b4e173785041f
        clientSecretValue: 70a6d6a76034f3fb641c83bc189e99f02fc86c4d

  external-dns:
    domainFilters: [aks.sandbox.cla.ns.nl]
    zoneIdFilters:
    azure:
      resourceGroup: dev-aks-dns
      aadClientId: 2f851cd5-a494-4a72-b17d-2eb3e6ad6214
      aadClientSecret: 25084581-8eec-4eeb-9c59-9bb9c7cd6097

  ingress-azure:
    armAuth:
      secretJSON: ewogICJjbGllbnRJZCI6ICI1MzI4M2IxYy04MDRkLTQ1OWMtYWM5My03YWQyNzVlNmJhMjEiLAogICJjbGllbnRTZWNyZXQiOiAiMTRmMzgyOGYtM2Y5Zi00ZTljLTk3YjYtM2FlZTEyNGFlNmE1IiwKICAic3Vic2NyaXB0aW9uSWQiOiAiMmU2OWEzMWEtNmNlZi00NDkzLWI4OTUtM2EwZDhlMTZlNThlIiwKICAidGVuYW50SWQiOiAiNjQ0NTgxNTktMGQ5YS00ZDg0LTk2NmYtMWExM2MwYWM3YTM0IiwKICAiYWN0aXZlRGlyZWN0b3J5RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tIiwKICAicmVzb3VyY2VNYW5hZ2VyRW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS8iLAogICJhY3RpdmVEaXJlY3RvcnlHcmFwaFJlc291cmNlSWQiOiAiaHR0cHM6Ly9ncmFwaC53aW5kb3dzLm5ldC8iLAogICJzcWxNYW5hZ2VtZW50RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmNvcmUud2luZG93cy5uZXQ6ODQ0My8iLAogICJnYWxsZXJ5RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9nYWxsZXJ5LmF6dXJlLmNvbS8iLAogICJtYW5hZ2VtZW50RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmNvcmUud2luZG93cy5uZXQvIgp9Cg==
    appgw:
      subscriptionId: 2e69a31a-6cef-4493-b895-3a0d8e16e58e
      resourceGroup: AKS20-sandbox
      name: AKS20-sandbox
      usePrivateIP: false
      subnetName: appgw-subnet
      subnetPrefix: 10.1.0.0/16

  istio:
    profile: default
    sds:
      enabled: false
    mtls:
      enabled: false
