hasCloudLB: true

azure:
  tenantId: 57a3f6ea-7e70-4260-acb4-e06ce452f695
  subscriptionId: 50c24abd-f872-4a3b-9f65-419800dda5eb
  diskType: standard # premium

charts:
  cert-manager:
    provider:
      azure:
        azuredns:
          clientID: ecc942ee-4f40-4612-8b30-465b5306cd31
          clientSecret: f93a4a07-140d-4520-a5b2-e6ae9d2e4974
          clientSecretSecretRef:
            name: cert-manager-sp
            key: CLIENT_SECRET
          tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
          subscriptionID: 50c24abd-f872-4a3b-9f65-419800dda5eb
          resourceGroupName: external-dns
          hostedZoneName: aks.otomi.cloud

  drone:
    sourceControl:
      github:
        clientID: eb64c85b4e173785041f
        clientSecretValue: 70a6d6a76034f3fb641c83bc189e99f02fc86c4d

  external-dns:
    domainFilters: [aks.otomi.cloud]
    zoneIdFilters:
    azure:
      resourceGroup: external-dns
      aadClientId: c328754d-b436-4828-aa72-a46a0d554670
      aadClientSecret: b864c0d5-116f-4f20-86d9-2021e8ea4113

  ingress-azure:
    armAuth:
      secretJSON: ewogICJjbGllbnRJZCI6ICJmOGYyYjQwNS05NTM3LTQ0MWItOGU4Ni00YWRhOWY4YmM2ODgiLAogICJjbGllbnRTZWNyZXQiOiAiZWY4ODQ3NzctMmM1Ny00N2U3LThlNjUtMzVhOThkZjIxNWY1IiwKICAic3Vic2NyaXB0aW9uSWQiOiAiNTBjMjRhYmQtZjg3Mi00YTNiLTlmNjUtNDE5ODAwZGRhNWViIiwKICAidGVuYW50SWQiOiAiNTdhM2Y2ZWEtN2U3MC00MjYwLWFjYjQtZTA2Y2U0NTJmNjk1IiwKICAiYWN0aXZlRGlyZWN0b3J5RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tIiwKICAicmVzb3VyY2VNYW5hZ2VyRW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmF6dXJlLmNvbS8iLAogICJhY3RpdmVEaXJlY3RvcnlHcmFwaFJlc291cmNlSWQiOiAiaHR0cHM6Ly9ncmFwaC53aW5kb3dzLm5ldC8iLAogICJzcWxNYW5hZ2VtZW50RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmNvcmUud2luZG93cy5uZXQ6ODQ0My8iLAogICJnYWxsZXJ5RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9nYWxsZXJ5LmF6dXJlLmNvbS8iLAogICJtYW5hZ2VtZW50RW5kcG9pbnRVcmwiOiAiaHR0cHM6Ly9tYW5hZ2VtZW50LmNvcmUud2luZG93cy5uZXQvIgp9Cg==
    appgw:
      subscriptionId: 50c24abd-f872-4a3b-9f65-419800dda5eb
      resourceGroup: otomi-aks-dev
      name: appgw-otomi-aks-dev
      usePrivateIP: false
      subnetName: appgw-subnet
      subnetPrefix: 10.1.0.0/16

  istio:
    profile: default
    sds:
      enabled: false
    mtls:
      enabled: false
