cluster:
  hasCloudLB: true
  useCloudCA: true
  hasKnative: false # only from k8s 1.15 up, and AWS has 1.14

ingress:
  certArns:
    # *.team-admin
    - arn:aws:acm:eu-central-1:059522483251:certificate/92e0cd2b-364a-4bf1-9af5-83b8d930048a
    # *.team-team1
    - arn:aws:acm:eu-central-1:059522483251:certificate/c90e0f89-da3f-4c3d-9476-b9895710ba21
    # hello.eks.otomi.cloud
    - arn:aws:acm:eu-central-1:059522483251:certificate/1bfbe1f6-0799-4cbd-a857-f57fa73f404d

charts:
  cert-manager:
    provider:
      aws:
        # see: https://cert-manager.io/docs/configuration/acme/dns01/route53/
        # we use metadata inferred
        route53:
          region: eu-west-1

  cluster-autoscaler:
    image:
      tag: v1.15.4

  drone:
    sourceControl:
      github:
        clientID: 68966e093b32da77269f
        clientSecretValue: 08cdbdd613b2700c49f17e38dc077faf2e765344

  external-dns:
    domainFilters: [otomi.cloud]
    zoneIdFilters:
    aws:
      region: eu-west-1

  istio:
    # profile: default
    # sds:
    #   enabled: false
    mtls:
      enabled: false
