hasCloudLB: false

cert-manager:
  stage: "staging"
  provider:
    aws:
      # see: https://cert-manager.io/docs/configuration/acme/dns01/route53/
      # we use metadata inferred
      route53:
        region: eu-central-1

drone:
  sourceControl:
    github:
      clientID: eb64c85b4e173785041f
      clientSecretValue: 70a6d6a76034f3fb641c83bc189e99f02fc86c4d

external-dns:
  domainFilters: [eks.otomi.cloud]
  zoneIdFilters:
  aws:
    region: eu-central-1

istio:
  # profile: default
  # sds:
  #   enabled: false
  mtls:
    enabled: false
