{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "otomi-web.serviceAccountName" . }}
  labels:
{{ include "otomi-web.labels" . | indent 4 }}
{{- end -}}
