otomi:
    mode: ce
    isManaged: true
    isMultitenant: true
    isHomeMonitored: true
    teamPrefix: team-
    hasCloudLB: false
customer:
    name: demo
oidc:
    clientID: otomi
    idp:
        issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695
        tenantID: 57a3f6ea-7e70-4260-acb4-e06ce452f695
        clientID: someClientID
        adminGroupID: someAdminGroupID
        teamAdminGroupID: someTeamAdminGroupID
    scope: openid email profile
alerts:
    drone: slack
    home:
        receivers: [slack]
        slack:
            channel: mon-otomi
            channelCrit: mon-otomi-crit
    receivers: [slack]
