apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otomi-api.fullname" . }}
  labels:
{{ include "otomi-api.labels" . | indent 4 }}
data:
  GIT_USER: {{ .Values.git.user| b64enc }}
  GIT_PASSWORD: {{ .Values.git.password| b64enc }}
