bases:
  - {{ env "ENV_DIR" | default "../env" }}/rendered-values.yaml
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: istio-artifacts
    installed: true
    namespace: istio-system
    labels:
      pkg: istio
    chart: ../charts/raw
    values:
      - ../values/raw/istio-raw.gotmpl
      - snippets/common.gotmpl
