bases:
  - snippets/defaults.yaml

{{ readFile "snippets/templates-skeleton.gotmpl" }}

releases:
  - name: cert-manager-init
    installed: true
    namespace: default
    labels:
      init: true
      tag: cert-manager
    <<: *skeleton # just install the stuff in k8s/apps/cert-manager
  - name: knative-init
    installed: true
    namespace: default
    labels:
      init: true
    <<: *skeleton
  - name: loki-artifacts
    installed: true
    namespace: monitoring
    chart: ../charts/raw
    labels:
      pkg: loki
    values:
    - ../values/loki/loki-raw.gotmpl
