bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: cluster-autoscaler
    installed: {{ eq $v.cluster.provider "aws" }}
    namespace: kube-system
    <<: *default
  # - name: istio-local-gw
  #   installed: {{ ge $v.cluster.k8sVersion 1.15 }}
  #   namespace: istio-system
  #   <<: *default
  - name: knative-serving
    installed: {{ ge $v.cluster.k8sVersion 1.15 }}
    namespace: knative-serving
    chart: ../charts/raw
    values:
      - ../values/knative/knative-serving-raw.gotmpl
  - name: gatekeeper-operator-config
    installed: true
    namespace: gatekeeper-system
    labels:
      pkg: gatekeeper-operator
    <<: *default
