bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: knative-init
    installed: {{ $v.cluster.hasKnative }}
    namespace: default
    labels:
      init: true
      pkg: knative
    <<: *skeleton
  - name: loki-artifacts
    installed: true
    namespace: monitoring
    labels:
      pkg: loki
    <<: *raw
  - name: flux
    installed: false # not ready yet
    namespace: maintenance
    <<: *default
  - name: gatekeeper-operator
    installed: true
    namespace: default
    labels:
      pkg: gatekeeper-operator
    <<: *default
  - name: prometheus-operator-crds
    installed: true
    namespace: monitoring
    labels:
      init: true
      pkg: prometheus-operator
    <<: *skeleton
