bases:
  - {{ env "ENV_DIR" | default "../env" }}/rendered-values.yaml
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: gitlab
    installed: false
    namespace: team-admin
    <<: *default
