bases:
  - snippets/defaults.yaml

{{ readFile "snippets/templates-skeleton.gotmpl" }}

releases:
  - name: cert-manager-init
    installed: true
    namespace: default
    labels:
      init: true
    <<: *skeleton # just install the stuff in k8s/apps/cert-manager

  - name: knative-init
    installed: true
    namespace: default
    labels:
      init: true
    <<: *skeleton

  - name: istio-init
    installed: true
    namespace: istio-system
    chart: ../charts/istio-init
    labels:
      init: true
    values:
    - ../values/istio/istio.gotmpl
