bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: hello
    # set 'installed' to true and set correct namespace for other customer demo on aws:
    installed: {{ and (eq $v.cluster.provider "aws") (eq $v.customerLabels.customer "otomi") }}
    namespace: team-otomi
    chart: ../charts/hello
    values:
      - nameOverride: hello
        fullnameOverride: hello
        image:
          tag: 1.1.3
