bases:
  - snippets/defaults.yaml

releases:
  - name: istio
    installed: true
    namespace: istio-system
    chart: ../charts/istio
    values:
    - ../values/istio/istio.gotmpl
    - ../values/default.gotmpl
