bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: maintenance-ingress-azure
    installed: {{ if eq $v.cluster.provider "azure" }}true{{ else }}false{{ end }}
    <<: *maintenance
    values:
      - namespace: ingress
        labels: app=ingress-azure
        schedule: "0 * * * *" # once an hour!
      - ../values/default.gotmpl
