bases:
  - {{ env "ENV_DIR" | default "../env" }}/rendered-values.yaml
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Values }}
{{- $a := $v.apps }}

releases:
  - name: job-gitea-prepare
    installed: {{ $a | get "gitea.enabled" }}
    labels:
      pkg: gitea
      group: jobs
    <<: *jobs