bases:
  - snippets/defaults.yaml
---
{{ readFile "snippets/templates.yaml" }}
{{- $v := .Environment.Values }}

releases:
  - name: cert-manager
    installed: true
    namespace: ingress
    labels:
      tag: cert-manager
    <<: *default
  - name: cert-manager-artifacts
    installed: true
    namespace: ingress
    chart: ../charts/raw
    labels:
      tag: cert-manager
    values:
    - ../values/cert-manager/cert-manager-raw.gotmpl
  - name: external-dns
    installed: true
    namespace: ingress
    <<: *default
  - name: dex
    installed: false
    namespace: ingress
    <<: *default
  - name: ingress-azure
    installed: {{ if eq $v.provider "azure" }}true{{ else }}false {{ end }}
    namespace: ingress
    <<: *default
  - name: ingress-azure-artifacts
    installed: {{ if eq $v.provider "azure" }}true{{ else }}false {{ end }}
    namespace: ingress
    chart: ../charts/raw
    labels:
      pkg: ingress-azure
    values:
    - ../values/ingress-azure/ingress-azure-raw.gotmpl
  - name: nginx-ingress
    installed: true
    namespace: ingress
    labels:
      tag: ingress
    <<: *default
  - name: nginx-ingress-artifacts
    installed: true
    namespace: istio-system
    chart: ../charts/raw
    labels:
      tag: ingress
    values:
    - ../values/nginx-ingress/nginx-ingress-raw.gotmpl
  - name: oauth2-proxy
    installed: true
    namespace: istio-system
    labels:
      tag: ingress
    <<: *default
