bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: aws-alb-ingress-controller
    installed: {{ if and (eq $v.provider "aws") ($v.hasCloudLB) }}true{{ else }}false{{ end }}
    namespace: ingress
    labels:
      tag: ingress
    <<: *default
  - name: cert-manager
    installed: true
    namespace: ingress
    labels:
      tag: cert-manager
    <<: *default
  - name: cert-manager-artifacts
    installed: true
    namespace: ingress
    chart: ../charts/raw
    labels:
      tag: cert-manager
    values:
    - ../values/cert-manager/cert-manager-raw.gotmpl
  - name: external-dns
    installed: true
    namespace: ingress
    <<: *default
  - name: ingress-azure
    installed: {{ if eq $v.provider "azure" }}true{{ else }}false{{ end }}
    namespace: ingress
    labels:
      tag: ingress
    <<: *default
  - name: nginx-ingress
    installed: true
    namespace: ingress
    labels:
      tag: ingress
    <<: *default
  - name: oauth2-proxy
    installed: true
    namespace: istio-system
    labels:
      tag: ingress
    <<: *default
