bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: cloud
    installed: true
    namespace: kube-system
    chart: ../charts/raw
    values:
    - ../values/cloud/cloud-raw.gotmpl
