bases:
  - snippets/defaults.gotmpl

---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}
{{- $c := $v.charts }}

releases:
  - name: harbor
    installed: {{ $c.harbor.enabled | default false }}
    namespace: harbor
    <<: *default
  - name: harbor-artifacts
    installed: {{ $c.harbor.enabled | default false }}
    namespace: harbor
    <<: *raw
  - name: otomi-api
    installed: true
    namespace: shared
    <<: *default
  - name: otomi-web
    installed: true
    namespace: shared
    <<: *default
  - name: redis-shared
    installed: {{ (index $c "redis-shared").enabled | default false }}
    namespace: shared
    <<: *default
