bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  - name: cert-manager
    installed: true
    namespace: ingress
    labels:
      tag: cert-manager
    <<: *default
  - name: cluster-autoscaler
    installed: {{ eq $v.cluster.provider "aws" }}
    namespace: kube-system
    <<: *default
  - name: istio-local-gw
    installed: {{ $v.cluster.hasKnative }}
    namespace: istio-system
    <<: *default
  - name: knative-serving
    installed: {{ $v.cluster.hasKnative }}
    namespace: knative-serving
    chart: ../charts/raw
    labels:
      pkg: knative
    values:
      - ../values/knative/knative-serving-raw.gotmpl
  - name: gatekeeper-operator-config
    installed: false
    namespace: gatekeeper-system
    labels:
      pkg: gatekeeper-operator
    <<: *default
