bases:
  - snippets/defaults.yaml
---
{{- $g := .Values }}
{{- $v := index $g "prometheus-operator" }}
{{- $t := readFile "../values/teams.yaml" | fromYaml }}
releases:
  {{- range $team := $t.teams }}
  # {{- $promHost := printf "prometheus.%s.%s" $team.name $g.teamDomain }}
  # {{- $alertsHost := printf "alertmanager.%s.%s" $team.name $g.teamDomain }}
  # {{- $grafanaHost := printf "grafana.%s.%s" $team.name $g.teamDomain }}
  {{- $promHost := printf "prometheus-%s.%s" $team.name $g.domain }}
  {{- $alertsHost := printf "alertmanager-%s.%s" $team.name $g.domain }}
  {{- $grafanaHost := printf "grafana-%s.%s" $team.name $g.domain }}
  - name: prometheus-team-{{ $team.name }}
    installed: true
    namespace: team-{{ $team.name }}
    chart: ../charts/prometheus-operator
    labels:
      tag: teams
    values:
      - ../values/prometheus-operator/prometheus-operator.gotmpl
      - ../values/prometheus-operator/prometheus-operator-team.gotmpl
      - nameOverride: {{ $team.name }}-po
        fullnameOverride: {{ $team.name }}-po
        alertmanager:
          alertmanagerSpec:
            externalUrl: https://{{ $alertsHost }}
          config:
            global:
              slack_api_url: {{ $team | get "slackUrl" $v.alertmanager.slackUrl }}
          receivers:
            - name: "null"
            - name: default
              slack_configs:
                - channel: "#mon-{{ $team.name }}"
                  {{- readFile "../values/prometheus-operator/slack-configs.yaml" | nindent 18 }}
            - name: critical
              slack_configs:
                - channel: "#mon-{{ $team.name }}-crit"
                  {{- readFile "../values/prometheus-operator/slack-configs.yaml" | nindent 18 }}
        prometheus:
          prometheusSpec:
            externalUrl: https://{{ $promHost }}
            ruleNamespaceSelector:
              matchLabels:
                name: team-{{ $team.name }}
            podMonitorNamespaceSelector:
              matchLabels:
                name: team-{{ $team.name }}
            serviceMonitorNamespaceSelector:
              matchLabels:
                name: team-{{ $team.name }}
        grafana:
          nameOverride: {{ $team.name }}-po-grafana
          fullnameOverride: {{ $team.name }}-po-grafana
          grafana.ini:
            server:
              root_url: https://{{ $grafanaHost }}
          additionalDataSources:
            # - name: Graphite
            #   editable: false
            #   type: graphite
            #   access: proxy
            #   url: http://graphite:80
            - name: Loki
              editable: false
              type: loki
              access: proxy
              url: http://loki.monitoring:11811
              basicAuth: true
              basicAuthUser: {{ $team.name }}
              basicAuthPassword: {{ $team.password }}
  - name: grafana-dashboards-{{ $team.name }}
    installed: true
    namespace: team-{{ $team.name }}
    chart: ../charts/grafana-dashboards
    labels:
      tag: teams
    values:
      - ../values/grafana-dashboards/grafana-dashboards.gotmpl
      - ../values/default.gotmpl
      - dashboards:
          default:
            kubernetes: null

  - name: index-{{ $team.name }}
    installed: true
    namespace: team-{{ $team.name }}
    chart: ../charts/index
    labels:
      tag: teams
    values:
      - ../values/index/index.gotmpl
      - ../values/default.gotmpl
      - fullnameOverride: {{ $team.name }}-index
        # domain: {{ printf "%s.%s" $team.name $g.teamDomain }}
        domain: {{ printf "%s.%s" $team.name $g.domain }}
        services: {{- $t.services | toYaml | nindent 10 }}
        group: {{ $team.name }}
        interpunct: "-"
  {{- end }}
