bases:
  - snippets/defaults.gotmpl
---
{{- $v := .Environment.Values }}

releases:
  - name: knative-serving
    installed: {{ if ge $v.cluster.k8sVersion 1.15 }}true{{ else }}false{{ end }}
    namespace: knative-serving
    chart: ../charts/raw
    values:
      - ../values/knative/knative-serving-raw.gotmpl
