bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}
{{- $v := .Environment.Values }}

releases:
  # cert-manager can't be installed as skeleton because it needs --validate=false, which is not
  # supported by helmfile, so we just apply by hand with:
  # k apply --validate=false -f k8s/cert-manager-init
  # - name: cert-manager-init
  #   installed: true
  #   namespace: default
  #   labels:
  #     init: true
  #     tag: cert-manager
  #   <<: *skeleton # just install the stuff in k8s/apps/cert-manager
  - name: knative-init
    installed: true
    namespace: default
    labels:
      init: true
    <<: *skeleton
  - name: loki-artifacts
    installed: true
    namespace: monitoring
    chart: ../charts/raw
    labels:
      pkg: loki
    values:
      - ../values/loki/loki-raw.gotmpl
