{{- $v := .Values }}
{{- if or (eq $v.teamId "admin") ($v.cluster.isMultitenant) }}
{{- $svc := (eq $v.teamId "admin" | ternary "oauth2-proxy" (printf "oauth2-proxy-team-%s" $v.teamId)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- include "ingress-annotations" . | nindent 4 }}
    ingress.kubernetes.io/ssl-redirect: {{ if $v.cluster.hasCloudLB }}"false"{{ else }}"true"{{ end }}
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # rewrite auth redirects to original hosts
      rewrite ^/oauth2/redirect/(.*) https://$1 redirect;
  labels: {{- include "chart-labels" . | nindent 4 }}
  name: auth-team-{{ $v.teamId }}
  namespace: istio-system
spec:
  rules:
  - host: 'apps.{{ $v.domain }}'
    http:
      paths:
      - backend:
          serviceName: {{ $svc }}
          servicePort: 80
        path: /oauth2/userinfo
  - host: 'auth.{{ $v.domain }}'
    http:
      paths:
      - backend:
          serviceName: {{ $svc }}
          servicePort: 80
        path: /oauth2
  {{- if not $v.cluster.hasCloudLB }}
  tls: 
    - secretName: cert-team-{{ $v.teamId }}-apps
      hosts:
        - 'apps.{{ $v.domain }}'
    - secretName: cert-team-{{ $v.teamId }}-auth
      hosts:
        - 'auth.{{ $v.domain }}'
  {{- end }}
{{- end }}
