{{- $v := .Values }}
{{- if and (eq $v.cluster.provider "aws") ($v.cluster.hasCloudLB) (or (eq $v.teamId "admin") ($v.cluster.isMultitenant)) }}
{{- $domains := list }}
{{- range $s := $v.services }}
{{- $shared := (and $s.isCore (eq $v.teamId "admin") (hasKey $s "isShared")) }}
{{- if and ($s.isCore) (or (hasKey $s "ownHost") $shared) (not (hasKey $s "hasCert")) (not (hasKey $s "host")) }}
{{- $domain := printf "%s.%s" $s.name ($shared | ternary $v.cluster.domain $v.domain) }}
{{- if not (has $domain $domains) }}
  {{- $domains = (append $domains $domain) }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq $v.teamId "admin" -}}
  {{- $proxyDomain := printf "proxy.%s" $v.domain }}
  {{- $domains = (append $domains $proxyDomain) }}
{{- end }}
{{- $appsDomain := printf "apps.%s" $v.domain }}
{{- $domains = (append $domains $appsDomain) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels: {{- include "chart-labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: merged-ingress
    alb.ingress.kubernetes.io/tags: "team=team-{{ $v.teamId }} {{ $v.ingress.tags }}"
  name: team-{{ $v.teamId }}
  namespace: ingress
spec:
  rules:
    {{- range $domain := $domains }}
    - host: {{ $domain }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
{{- end }}
