{{- $v := .Values }}
{{- if and (eq $v.cluster.provider "aws") ($v.cluster.hasCloudLB) (or (eq $v.teamId "admin") ($v.cluster.isMultitenant)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels: {{- include "chart-labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: merge
    merge.ingress.kubernetes.io/config: merged-ingress
    alb.ingress.kubernetes.io/tags: "team=team-{{ $v.teamId }} {{ $v.ingress.tags }}"
  name: team-{{ $v.teamId }}
  namespace: ingress
spec:
  rules:
    {{- range $s := $v.services }}
    {{- if and (not $s.internal) (not $s.host) (hasKey $s "domain") }}
    {{- $domain := index $s "domain" }}
    - host: {{ $domain }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
    {{- end }}
    {{- range $app := list "auth" "apps" "proxy" }}
    - host: {{ $app }}.{{ $v.domain }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
{{- end }}
{{- if eq $v.teamId "admin" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: merged-ingress
  namespace: ingress
data:
  annotations: |
    provider: aws
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- if $v.ingress.certArns }}
    alb.ingress.kubernetes.io/certificate-arn: {{ include "helm-toolkit.utils.joinListWithComma" $v.ingress.certArns  | quote }}
    {{- end }}
    {{- if $v.ingress.allowedCidrs }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ include "helm-toolkit.utils.joinListWithComma" $v.ingress.allowedCidrs  | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/success-codes: '200,302,404'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    {{- if $v.ingress.disableHttp2 }}
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=false"
    {{- end }}
{{- end }}
