{{ $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- if and (eq $v.provider "azure") ($v.hasCloudLB) }}
{{- $domConnector := $v.ingress.domConnector }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $ns }}
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "{{ if $v.ingress.forceSsl }}true{{ else }}false{{ end }}"
    appgw.ingress.kubernetes.io/backend-protocol: "{{ if $v.ingress.forceSsl }}https{{ else }}http{{ end }}"
    provider: azure
spec:
  tls:
    {{- range $s := concat $v.coreServices ($v.services | default list) }}
    {{- $host := $s.domain | default (printf "%s%s%s" ($s.host | default $s.name) $domConnector $v.domain) }}
    - hosts:
        - {{ $host }}
      secretName: letsencrypt-{{ $v.certStage }}-k8s
    {{- end }}
  rules:
    {{- range $s := concat $v.coreServices ($v.services | default list) }}
    {{- $host := $s.domain | default (printf "%s%s%s" ($s.host | default $s.name) $domConnector $v.domain) }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
{{- end }}
