{{- $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- $services := concat $v.coreServices $v.services | default list }}
{{- if and (eq $v.provider "azure") ($v.hasCloudLB) (not (eq (len $services) 0)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appgw-{{ $ns }}
  namespace: ingress
  labels: {{- template "chart-labels" . | toYaml | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    provider: azure
spec:
  tls:
    {{- range $s := $services }}
    {{- $domain := printf "%s.%s" $s.name $v.domain }}
    - hosts:
        - {{ $domain }}
      secretName: letsencrypt-{{ $v.certStage }}-{{ $v.name }}
    {{- end }}
  rules:
    {{- range $s := $services }}
    {{- $domain := printf "%s.%s" $s.name $v.domain }}
    - host: {{ $domain }}
      http:
        paths:
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
{{- end }}
