{{- $v := .Values }}
{{- if and (eq $v.cluster.provider "azure") ($v.cluster.hasCloudLB) (or (eq $v.teamId "admin") ($v.cluster.isMultitenant)) }}
{{- $domains := list }}
{{- range $s := $v.services }}
{{- $shared := (and $s.isCore (eq $v.teamId "admin") (hasKey $s "isShared")) }}
{{- if and ($s.isCore) (or (hasKey $s "ownHost") $shared) (not (hasKey $s "hasCert")) (not (hasKey $s "host")) }}
{{- $domain := printf "%s.%s" $s.name ($shared | ternary $v.cluster.domain $v.domain) }}
{{- if not (has $domain $domains) }}
  {{- $domains = (append $domains $domain) }}
{{- end }}
{{- end }}
{{- end }}
{{- if eq $v.teamId "admin" -}}
  {{- $proxyDomain := printf "proxy.%s" $v.domain }}
  {{- $domains = (append $domains $proxyDomain) }}
{{- end }}
{{- $appsDomain := printf "apps.%s" $v.domain }}
{{- $domains = (append $domains $appsDomain) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appgw-team-{{ $v.teamId }}
  namespace: ingress
  labels: {{- include "chart-labels" . | nindent 4 }}
  annotations:
    provider: azure
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
    {{- range $domain := $domains }}
    - host: {{ $domain }}
      http:
        paths:
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
  tls:
    {{- range $domain := $domains }}
    - hosts:
        - {{ $domain }}
      secretName: {{ $domain | replace "." "-" }}
    {{- end }}
{{- end }}
