{{- $v := .Values }}
{{- if and (eq $v.provider "azure") ($v.hasCloudLB) (or (eq $v.name "admin") ($v.isMultitenant)) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: appgw-team-{{ $v.name }}
  namespace: ingress
  labels: {{- include "chart-labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    provider: azure
spec:
  tls:
    {{- range $s := $v.services }}
    {{- if (not $s.private) -}}
    {{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) }}
    {{- $name := (hasKey $s "domain" | ternary $s.name $v.name) }}
    - hosts:
        - {{ $domain }}
      secretName: cert-team-{{ $v.name }}-{{ $name }}
    {{- end }}
    {{- end }}
  rules:
    {{- range $s := $v.services }}
    {{- if (not $s.private) -}}
    {{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) }}
    - host: {{ $domain }}
      http:
        paths:
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
    {{- end }}
    {{- end }}
{{- end }}
