{{- $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- $services := concat $v.coreServices $v.services }}
{{- if and (not (eq (len $services) 0)) (not (and (eq $v.provider "aws") ($v.hasCloudLB))) }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-{{ $v.certStage }}-{{ $v.name }}
  namespace: {{ if $v.hasCloudLB }}ingress{{ else }}istio-system{{ end }}
  labels: {{- template "chart-labels" . | nindent 4 }}
spec:
  secretName: letsencrypt-{{ $v.certStage }}-{{ $v.name }}
  commonName: "*.{{ $v.domain }}"
  dnsNames:
  - "*.{{ $v.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ $v.certStage }}
{{- end }}
