{{- $v := .Values }}
{{- if and (not $v.cluster.useCloudCA) (or (eq $v.teamId "admin") ($v.cluster.isMultitenant)) }}
# collect unique host names
{{- $hosts := list }}
{{- range $s := $v.services }}
{{- if and ($s.isCore) (or (hasKey $s "ownHost") (hasKey $s "isShared")) }}
{{- $domain := printf "%s.%s" $s.name (eq $s.namespace "shared" | ternary $v.cluster.domain $v.domain) }}
{{- if not (has $domain $hosts) }}
  {{- $hosts = (append $hosts $domain) }}
{{- end }}
{{- end }}
{{- end }}
{{- $appsDomain := printf "apps.%s" $v.domain }}
{{- $hosts := (append $hosts $appsDomain) }}
{{- range $host := $hosts }}
{{ $name := $host | replace "." "-" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ if $v.cluster.hasCloudLB }}ingress{{ else }}istio-system{{ end }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  secretName: {{ $name }}
  commonName: "{{ $host }}"
  dnsNames:
  - "{{ $host }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ $v.certStage }}
  usages:
    - digital signature
    - key encipherment
    - ocsp signing
---
{{- end }}
{{- end }}
