{{- $v := .Values }}
{{- if and (not $v.useCloudCA) (or (eq $v.name "admin") ($v.isMultitenant)) }}
{{- $ := . }}
{{ $name := printf "cert-team-%s" $v.name }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ if $v.hasCloudLB }}ingress{{ else }}istio-system{{ end }}
  labels: {{- include "chart-labels" . | nindent 4 }}
spec:
  secretName: {{ $name }}
  commonName: "*.{{ $v.domain }}"
  dnsNames:
  - "*.{{ $v.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ $v.certStage }}
---
{{- range $s := $v.services }}
{{- if and (not $s.hasCert) (hasKey $s "domain") }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $name }}-{{ $s.name }}
  namespace: {{ if $v.hasCloudLB }}ingress{{ else }}istio-system{{ end }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  secretName: {{ $name }}-{{ $s.name }}
  commonName: "{{ $s.domain }}"
  dnsNames:
  - "{{ $s.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-{{ $v.certStage }}
---
{{- end }}
{{- end }}
{{- end }}
