{{- $v := .Values }}

apiVersion: v1
data:
  kconfig.sh: |
    mkdir "${HOME}/.kube"
    KUBECONFIG="${HOME}/.kube/config"
    TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
    CA_CRT="$(base64 -w 0 /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)"
    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

    cat <<EOF > "${KUBECONFIG}"
    apiVersion: v1
    kind: Config
    clusters:
    - name: otomi
      cluster:
        certificate-authority-data: ${CA_CRT}
        server: https://kubernetes.default.svc.cluster.local
    contexts:
    - name: default-context
      context:
        cluster: otomi
        namespace: ${NAMESPACE}
        user: team-demo-user
    current-context: default-context
    users:
    - name: team-demo-user
      user:
        token: ${TOKEN}
    EOF
kind: ConfigMap
metadata:
  name: kconfig
  namespace: team-{{ $v.teamId }}

