{{- $v := .Values }}
{{- $ := . }}
{{- range $s := $v.externalSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $s.name }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
    {{- with $s.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  backendType: vault
  vaultMountPoint: 'kubernetes'
  vaultRole: default
  template:
  {{- if eq $s.type "tls" }}
    type: kubernetes.io/tls
  data:
    - key: {{ $s.tlsCrtPAth }}
      property: crt
      name: {{ $s.tlsCrtFileName }}
    - key: {{ $s.tlsKeyPath }}
      property: key
      name: {{ $s.tlsKeyFileName }}
    - key: {{ $s.caCrtPath }}
      property: ca
      name: {{ $s.caCrtFileName }}
  {{- else if eq $s.type "genericItem" }}
    type: Opaque
  data:
    - key: {{ .vaultPath }}
      name: {{ .vaultProperty }}
      property: {{ .vaultProperty }}
  {{- else if eq $s.type "generic" }}
    type: Opaque
  dataFrom:
    - {{ $s.vaultPath }}
  {{- else if eq $s.type "docker-registry" }}
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ $s.vaultPath }}
      name: .dockerconfigjson
  {{ end }}
---      
{{- end }}
