{{- $v := .Values }}
{{- $ := . }}
{{- range $s := $v.externalSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $s.name }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
    {{- with $s.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  backendType: vault
  vaultMountPoint: 'kubernetes'
  vaultRole: default
  template:
  {{- if eq $s.type "tls" }}
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ $s.tlsCrt }}
      property: crt
      name: tls.crt
    - key: {{ $s.tlsKey }}
      property: key
      name: tls.key
    - key: {{ $s.caCrt }}
      property: ca
      name: ca.crt
  {{- else if eq $s.type "generic" }}
    type: Opaque
    {{- if hasKey $s data }}
  data:
    {{- range $s.data }}
    - key: {{ .key }}
      name: {{ .name }}
      property: {{ .property }}
    {{- end }}
  {{- else if hasKey $s dataFrom }}
  dataFrom:
    - {{ $s.dataFrom }}
  {{- end }}
  {{- else if eq $s.type "docker-registry" }}
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ $s.path }}
      name: .dockerconfigjson
  {{ end }}
---      
{{- end }}
