{{- $v := .Values }}
{{- if get (index $v.apps "external-secrets") "enabled" }}
{{- $pathPrefix := printf "secret/data/teams/team-%s" $v.teamId }}
{{- range $s := $v.secrets }}
{{- $vaultPath := printf "%s/%s" $pathPrefix $s.name | quote }}
{{- if eq $s.type "tls" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: tls-secret-copy
    namespace: ingress
spec:
    refreshInterval: 1m
    secretStoreRef:
        name: vault-backend
        kind: ClusterSecretStore
    target:
        name: copy-{{ $v.teamId }}-{{ $v.secretName }}
        creationPolicy: Owner
    dataFrom:
    - extract:
        key: {{ $vaultPath }}
        property: {{ $s.crt | default "tls.crt" }}
        secretKey: tls.crt
    - extract:
        key: {{ $vaultPath }}
        property: {{ $s.key | default "tls.key" }}
        secretKey: tls.key
{{- if hasKey $s "ca" }}
    - extract:
        key: {{ $vaultPath }}
        property: {{ $s.ca | default "ca.crt" }}
        secretKey: ca.crt
{{- end }}
{{- end }}
{{- end }}
{{- end }}
