{{- $v := .Values }}
{{- if get (index $v.apps "external-secrets") "enabled" }}
    {{- $pathPrefix := printf "secret/data/teams/team-%s" $v.teamId }}
    {{- range $s := $v.secrets }}
        {{- $vaultPath := printf "%s/%s" $pathPrefix $s.name | quote }}
        {{- if eq $s.type "docker-registry" }}
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
            name: dockerconfig-secret-copy
            namespace: argocd
        spec:
            refreshInterval: 1m
            secretStoreRef:
                name: vault-backend
                kind: ClusterSecretStore
            target:
                name: copy-{{ $v.teamId }}-{{ $v.secretName }}
                creationPolicy: Owner
            dataFrom:
            - extract:
                key: {{ $vaultPath }}
                secretKey: ".dockerconfigjson"
        {{- end }}
    {{- end }}
{{- end }}
