{{- $v := .Values }}
{{- $ := . }}
{{- range $s := $v.externalSecrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $s.name }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
    {{- with $s.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  backendType: vault
  vaultMountPoint: 'kubernetes'
  vaultRole: default
  template:
  {{- if eq $s.type "tls" }}
    type: kubernetes.io/tls
  data:
    - key: {{ $s.crtSecretPath }}
      property: {{ $s.crtItemName | default "crt.pem" }}
      name: {{ $s.crtItemName | default "crt.pem" }}
    - key: {{ $s.keySecretPath }}
      property: {{ $s.keyItemName | default "key.pem" }}
      name: {{ $s.keyItemName | default "key.pem" }}
    {{- if hasKey $s "caSecretPath" }}
    - key: {{ $s.caSecretPath }}
      property: {{ $s.caItemName | default "ca.pem" }}
      name: {{ $s.caItemName | default "ca.pem" }}
    {{- end }}
  {{- else if eq $s.type "generic" }}
    type: Opaque
  data:
    {{- range .entries }}
    - key: {{ .value }}
      name: {{ .name }}
      property: {{ .name }}
    {{- end }}
  {{- else if eq $s.type "docker-registry" }}
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ $s.secretPath }}
      name: ".dockerconfigjson"
  {{- end }}
---      
{{- end }}
