{{- $v := .Values }}
{{- if or (eq $v.teamId "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- if hasKey $s "mtls" }}
{{- if or (hasKey $s.mtls "gatewayDisabled") (hasKey $s.mtls "policyMode") }}
# yyy
{{- $mode := (index $s.mtls "policyMode" | default "permissive") }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- $svc := (hasKey $s "hasPrefix" | ternary (printf "%s-%s" $v.teamId $s.name) $s.name) }}
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: team-{{ $v.teamId }}-{{ $s.name }}-{{ $mode }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  peers:
    - mtls:
        mode: {{ $mode | upper }}
  targets:
    - name: {{ $svc }}.{{ $ns }}.svc.cluster.local
---    
{{- end }}
{{- end }}
{{- end }}
{{- end }}
