{{- $v := .Values }}
{{- if or (eq $v.name "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- if and (not (hasKey $s "internal")) (not (hasKey $s "host")) (or (hasKey $s "svc") (hasKey $s "domain")) }}
{{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $s.name }}-{{ $domain | replace "." "-" }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  gateways:
  {{- if hasKey $s "ksvc" }}
  - knative-serving/knative-ingress-gateway
  {{- else }}
  - {{ $.Release.Namespace }}/team-{{ $v.name }}
  {{- end }}
  hosts:
  - {{ $domain }}
  http: 
  {{- if hasKey $s "ksvc" }}
    - rewrite:
        authority: {{ $s.svc }}.{{ $v.domain }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
  {{- else }}
    - route:
        - destination:
            host: {{ $s.svc }}.{{ $ns }}.svc.cluster.local
  {{- end }}
            port:
              number: {{ index $s "port" | default 80 }}
          weight: 100
---      
{{- end }}
{{- end }}
{{- end }}
