{{- $v := .Values }}
{{- if or (eq $v.name "admin") ($v.isMultitenant) }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: team-{{ $v.name }}
  labels: {{- include "chart-labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
      - '*.{{ $v.domain }}'
      {{- range $s := $v.services }}
      {{- if and (hasKey $s "domain") (index $s "svc") }}
      - {{ $s.domain }}
      {{- end }}
      {{- end }}
    port:
      name: http
      number: 80
      protocol: HTTP
{{- end }}
