{{- $v := .Values }}
{{- if or (eq $v.teamId "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- if and (not $s.internal) (not (hasKey $s "host")) }}
{{- $svc := (hasKey $s "hasPrefix" | ternary (printf "%s-%s" $v.teamId ($s.svc | default $s.name)) ($s.svc | default $s.name)) }}
{{- $shared := (and $s.isCore (eq $v.teamId "admin") (hasKey $s "isShared")) | default false}}
{{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name ($shared | ternary $v.cluster.domain $v.domain))) }}
{{/*- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) */}}
{{- $vsName := printf "%s%s" ($domain | replace "." "-") (hasKey $s "path" | ternary (printf "-%s" (($s.path | default "") | replace "/" "")) "") -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $vsName }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  gateways:
  {{- if hasKey $s "ksvc" }}
  - knative-serving/knative-ingress-gateway
  {{- else }}
  - {{ $.Release.Namespace }}/team-{{ $v.teamId }}
  {{- end }}
  hosts:
  - {{ $domain }}
  {{- if $s.tlsPass }}
  tls:
  {{- else }}
  http:
  {{- end }}
    - match:
    {{- if $s.tlsPass }}
        - port: 443
          sniHosts:
            - {{ $domain }}
    {{- else }}
        - port: 80
      {{- if and (hasKey $s "path") (not $s.tlsPass) }}
          uri:
            prefix: "{{ $s.path }}"
        {{- if not (hasKey $s "forwardPath") }}
      rewrite:
        uri: "/"
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if hasKey $s "ksvc" }}
      rewrite:
        authority: {{ $s.name }}.{{ $v.domain }}
      {{- if hasKey $s "path" }}
        uri: "/"
      {{- end }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
    {{- else }}
      route:
        - destination:
            host: {{ $svc }}.{{ $ns }}.svc.cluster.local
    {{- end }}
            port:
              number: {{ $s.port | default (hasKey $s "tlsPass" | ternary 443 80) }}
      # fix for istio (=envoy) incorrectly setting proto to http
      # (@see https://github.com/istio/istio/issues/7964):
      appendHeaders:
        'x-forwarded-proto': 'https'
        'x-forwarded-port': '443'          
---      
{{- end }}
{{- end }}
{{- end }}
