{{- $v := .Values }}
{{- if and (not $v.cluster.useCloudCA) (or (eq $v.name "admin") ($v.cluster.isMultitenant)) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- if (index $s "mtls.gatewayDisabled") }}
{{- $ns := index $s "namespace" | default .Release.Namespace }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $s.name }}-notls
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  host: {{ $s.svc }}.{{ $ns }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
---      
{{- end }}
{{- end }}
{{- end }}
