{{- $v := .Values }}
{{- if or (eq $v.teamId "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- if and (not $s.internal) (not (hasKey $s "host")) }}
{{- $svc := (hasKey $s "hasPrefix" | ternary (printf "%s-%s" $v.teamId ($s.svc | default $s.name)) ($s.svc | default $s.name)) }}
{{- $shared := eq "shared" ($s.namespace | default "") }}
{{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name ((and (hasKey $s "ownHost") $shared) | ternary $v.cluster.domain $v.domain))) }}
{{/*- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) */}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $domain | replace "." "-" }}-{{ $s.path | default "x" | replace "/" "" }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  gateways:
  {{- if hasKey $s "ksvc" }}
  - knative-serving/knative-ingress-gateway
  {{- else }}
  - {{ $.Release.Namespace }}/team-{{ $v.teamId }}
  {{- end }}
  hosts:
  - {{ $domain }}
  http:
    - name: {{ $domain | replace "." "-" }}-{{ $s.path | default "x" | replace "/" "" }}
  {{- if hasKey $s "path" }}
      match:
        - uri:
            prefix: "{{ $s.path }}"
      {{- if not (hasKey $s "forwardPath") }}
      rewrite:
        uri: "/"
      {{- end }}
  {{- end }}
  {{- if hasKey $s "ksvc" }}
      rewrite:
        authority: {{ $s.name }}.{{ $v.domain }}
    {{- if hasKey $s "path" }}
        uri: "/"
    {{- end }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
  {{- else }}
      route:
        - destination:
            host: {{ $svc }}.{{ $ns }}.svc.cluster.local
  {{- end }}
            port:
              number: {{ index $s "port" | default 80 }}
          weight: 100
      # fix for istio (=envoy) incorrectly setting proto to http
      # (@see https://github.com/istio/istio/issues/7964):
      appendHeaders:
        'x-forwarded-proto': 'https'
        'x-forwarded-port': '443'          
---      
{{- end }}
{{- end }}
{{- end }}
