{{- $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- $services := concat $v.coreServices $v.services }}
{{- range $s := $services }}
{{- if or (index $s "mtls.gatewayDisabled") (index $s "mtls.policyMode") }}
{{- $mode := ($s | get "mtls.policyMode" "permissive") }}
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: {{ $s.name }}-{{ $mode }}
  labels: {{- template "chart-labels" . | toYaml | nindent 4 }}
spec:
  peers:
    - mtls:
        mode: {{ $mode | upper }}
  targets:
    - name: {{ $s.svc }}
{{- end }}
{{- end }}
