{{- $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- $ := . }}
{{- $services := concat $v.coreServices $v.services }}
{{- range $s := $services }}
{{- if and (not (index $s "private")) (not (index $s "virtual")) (index $s "svc") }}
{{- $domain := printf "%s.%s" $s.name $v.domain }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $s.name }}-{{ $v.domain | replace "." "-" }}
  labels: {{- template "chart-labels" . | toYaml | nindent 4 }}
spec:
  gateways:
  - {{ $ns }}/{{ $v.name }}
  hosts:
  - {{ $domain }}
  http:
  - route:
    - destination:
        host: {{ $v.name }}-{{ $s.svc }}.{{ $ns }}.svc.cluster.local
        port:
          number: {{ index $s "port" | default 80 }}
      weight: 100
---      
{{- end }}
{{- end }}
