{{- $v := .Values }}
{{- if or (eq $v.teamId "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- if and (not (hasKey $s "internal")) (not (hasKey $s "host")) (or (hasKey $s "svc") (hasKey $s "domain")) }}
{{- $svc := (hasKey $s "hasPrefix" | ternary (printf "%s-%s" $v.teamId $s.svc) $s.svc) }}
{{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $s.name }}-{{ $domain | replace "." "-" }}-{{ $s.path | default "x" | replace "/" "" }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  gateways:
  {{- if hasKey $s "ksvc" }}
  - knative-serving/knative-ingress-gateway
  {{- else }}
  - {{ $.Release.Namespace }}/team-{{ $v.teamId }}
  {{- end }}
  hosts:
  - {{ $domain }}
  http:
    - name: {{ $s.name }}-{{ $domain | replace "." "-" }}-{{ $s.path | default "x" | replace "/" "" }}
  {{- if hasKey $s "ksvc" }}
      rewrite:
        authority: {{ $s.name }}.{{ $v.domain }}
      route:
        - destination:
            host: istio-ingressgateway.istio-system.svc.cluster.local
  {{- else }}
      {{- if hasKey $s "path" }}
      match:
        - uri:
            prefix: "{{ $s.path }}/"
      rewrite:
        uri: "/"
      {{- end }}
      route:
        - destination:
            host: {{ $svc }}.{{ $ns }}.svc.cluster.local
  {{- end }}
            port:
              number: {{ index $s "port" | default 80 }}
          weight: 100
---      
{{- end }}
{{- end }}
{{- end }}
