{{- $v := .Values }}
{{- if or (eq $v.name "admin") ($v.cluster.isMultitenant) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- $ns := index $s "namespace" | default $.Release.Namespace }}
{{- if and (not (index $s "internal")) (not (index $s "host")) (hasKey $s "svc") }}
{{- $domain := (index $s "domain" | default (printf "%s.%s" $s.name $v.domain)) }}
{{- $svc := (eq $v.name "admin") | ternary $s.svc (hasKey $s "svc" | ternary (printf "%s-%s" $v.name $s.svc) $s.name) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $s.name }}-{{ $v.domain | replace "." "-" }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  gateways:
  - {{ $.Release.Namespace }}/team-{{ $v.name }}
  hosts:
  - {{ $domain }}
  http:
  - route:
    - destination:
        host: {{ $svc }}.{{ $ns }}.svc.cluster.local
        port:
          number: {{ index $s "port" | default 80 }}
      weight: 100
---      
{{- end }}
{{- end }}
{{- end }}
