{{- $v := .Values }}
{{- if (index $v "knative.enabled" | default "true") }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- if and (not (index $s "internal")) (not (index $s "host")) (index $s "ksvc") }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $s.name }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
spec:
  template:
    metadata:
    {{- with $s.ksvc.annotations }}
      annotations:
        bla: dida
    {{- end }}
    spec:
      containers:
        - image: {{ $s.ksvc.image.repository }}:{{ $s.ksvc.image.tag }}
          env:
            - name: TEAM_NAME
              value: {{ $s.name }}
            {{- if hasKey $s "env" }}
            {{- $s.env | toYaml | nindent 12 }}
            {{- end }}
---      
{{- end }}
{{- end }}
{{- end }}
