{{- $v := .Values }}
{{- if (get $v "knative.enabled" | default true) }}
{{- $ := . }}
{{- range $s := $v.services }}
{{- if hasKey $s "ksvc" }}
{{- $k := $s.ksvc }}
{{- if not $k.predeployed }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ $s.name }}
  labels: {{- include "chart-labels" $ | nindent 4 }}
    {{- with $k.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    {{- if $s.internal }}
    serving.knative.dev/visibility: cluster-local
    {{- end }}
spec:
  template:
    metadata:
      annotations:
        {{- if (index $k "autoCD") }}
        fluxcd.io/automated: 'true'
        fluxcd.io/tag.user-container: "{{ $k.autoCD.tagMatcher | default "semver" }}:{{ index $k.autoCD $k.autoCD.tagMatcher }}"
        {{- end }}
        {{- with $k.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- if not (hasKey $k "scaleToZero") }}
        autoscaling.knative.dev/minScale: '1'
        {{- end }}
    spec:
      containers:
        - image: {{ $k.image.repository }}:{{ $k.image.tag }}
          env:
            - name: TEAM_NAME
              value: {{ $s.name }}
            {{- with $k.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          {{- with $k.envFrom }}
          envFrom: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $k.resources }}
          resources: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $k.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $k.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
---      
{{- end }}
{{- end }}
{{- end }}
{{- end }}
