{{- $ns := .Release.Namespace }}
{{- $v := .Values }}
{{- $gcr := $v.secret.gcr }}
apiVersion: v1
data:
  .dockerconfigjson: {{ $gcr.data }}
kind: Secret
metadata:
  name: {{ $gcr.name }}
  namespace: {{ $ns }}
  labels: {{- include "chart-labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
---