{{- if .Values.appgw -}}
{{- if .Values.appgw.shared -}}
apiVersion: appgw.ingress.k8s.io/v1
kind: AzureIngressProhibitedTarget
metadata:
  name: prohibit-all-targets
spec:
  paths:
    - /*
{{- end -}}
{{- end -}}
