provider: ""
adminDomain: ""
hasCloudLB: false
certStage: staging
namespace: ""
resourceQuota:
  pods: "50"
  persistentvolumeclaims: "1"
  services.loadbalancers: "0"
  resourcequotas: "1"  
ingress:
  allowedCidrs: []
  certArns: []
  tags: ""
  forceSsl: true
  disableHttp2: false
  domConnector: "."
services: []  