toolsVersion: 1.1.2
provider: ""
adminDomain: ""
hasCloudLB: false
certStage: staging
namespace: ""
resourceQuota:
  pods: "50"
  persistentvolumeclaims: "1"
  services.loadbalancers: "0"
  resourcequotas: "1"  
ingress:
  allowedCidrs: []
  certArns: []
  tags: ""
  disableHttp2: false
services: []
proxies: []
region: ""
authAnnotations: {}
ingressAnnotations: {}
knative:
  enabled: true
  config: {}
    # domain:
    #   customdomain.com: |
    #     app: prod
limitRange:
  default:
    cpu: 100m
    memory: 128Mi
  defaultRequest:
    cpu: 50m
    memory: 64Mi

