apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
spec:
  hosts:
  - "dex.localhost.local"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        prefix: /dex
    - uri:
        prefix: /login
    - uri:
        prefix: /logout
    route:
    - destination:
        host: dex.auth.svc.cluster.local
        port:
          number: 5556