apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dex
  namespace: default
spec:
  hosts:
  - "dex.localhost.local"
  gateways:
  - bookinfo-gateway
  http:
  - route:
    - destination:
        host: dex.auth.svc.cluster.local
        port:
          number: 5556