  config.yaml: |
    issuer: http://dex.auth.svc.cluster.local:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: admin@kubeflow.org
      hash: $2y$12$ruoM7FqXrpVgaol44eRZW.4HWS8SAvg6KYVVSCIwKQPBmTpCm.EeO
      username: admin
      userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
    staticClients:
    - id: kubeflow-oidc-authservice
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
    connectors:
    - type: oidc
      id: azuread
      name: AzureAD
      config:
        # Canonical URL of the provider, also used for configuration discovery.
        # This value MUST match the value returned in the provider config discovery.
        #
        # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
        issuer: https://login.microsoftonline.com/57a3f6ea-7e70-4260-acb4-e06ce452f695/v2.0
        # https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

        # Connector config values starting with a "$" will read from the environment.
        clientID: 5eb129f2-1b26-4910-a05a-70d8b6a380cd
        clientSecret: "CKH?8FXb5l8DE:ea=B0_kwWw5SnIIQ-y"

        # Dex's issuer URL + "/callback"
        redirectURI: http://dex.auth.svc.cluster.local:5556/dex/callback

        scopes:
        - profile
        - email