apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    name: system
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otomi-admin
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: otomi-admin
subjects:
  - kind: ServiceAccount
    name: otomi-admin
    namespace: system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otomi-admin:psp:unrestricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unrestricted
subjects:
- kind: ServiceAccount
  name: otomi-admin
  namespace: system
