apiVersion: v1
kind: Namespace
metadata:
  name: tillerless
  labels:
    name: tillerless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tillerless
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: tillerless
rules: 
- apiGroups: [""] 
  resources: ["secrets", "configmaps", "pods", "services"] 
  verbs: ["*"]
- apiGroups: ["extensions"] 
  resources: ["deployments"] 
  verbs: ["*"]
- apiGroups: ["apps"] 
  resources: ["deployments"] 
  verbs: ["*"]