apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: otomi-task
  namespace: team-admin
spec:
  params:
    - name: repoUrl
      type: string
      description: Repository Url
      default: No Repo provided!
    - name: otomi-version
      type: string
      default: 'v1.0.0'
    - name: gitea_user
      type: string
      default: 'otomi-admin'
    - name: gitea_password
      type: string
      default: 'welcomeotomi'
  workspaces:
    - name: shared
      mountPath: /home/app/stack/env
  steps:
    - name: git-clone
      image: otomi/core:$(params["otomi-version"])
      workingDir: $(workspaces.shared.path)
      env:
        - name: AZURE_CLIENT_ID
          value: <inser-value>
        - name: AZURE_CLIENT_SECRET
          value: <inser-value>
        - name: AZURE_TENANT_ID
          value: <inser-value>
        - name: CI
          value: '1'
        - name: IN_DOCKER
          value: '1'
      command:
        - '/bin/bash'
      args:
        - '-c'
        - 'repoUrl=$(params["repoUrl"]) && url=${repoUrl/"https://"/} && git clone -c http.sslVerify=false https://$(params["gitea_user"]):$(params["gitea_password"])@$url .'
    - name: bootstrap
      image: otomi/core:v1.0.0
      workingDir: $(workspaces.shared.path)
      env:
        - name: AZURE_CLIENT_ID
          value: <inser-value>
        - name: AZURE_CLIENT_SECRET
          value: <inser-value>
        - name: AZURE_TENANT_ID
          value: <inser-value>
        - name: CI
          value: '1'
        - name: IN_DOCKER
          value: '1'
      command:
        - '/bin/bash'
      args:
        - '-c'
        - 'cd .. && binzx/otomi bootstrap'
    - name: test
      image: otomi/core:v1.0.0
      workingDir: $(workspaces.shared.path)
      env:
        - name: AZURE_CLIENT_ID
          value: <inser-value>
        - name: AZURE_CLIENT_SECRET
          value: <inser-value>
        - name: AZURE_TENANT_ID
          value: <inser-value>
        - name: CI
          value: '1'
        - name: IN_DOCKER
          value: '1'
      command:
        - '/bin/bash'
      args:
        - '-c'
        - 'cd .. && binzx/otomi validate-values'
    - name: apply
      image: otomi/core:v1.0.0
      workingDir: $(workspaces.shared.path)
      env:
        - name: AZURE_CLIENT_ID
          value: <inser-value>
        - name: AZURE_CLIENT_SECRET
          value: <inser-value>
        - name: AZURE_TENANT_ID
          value: <inser-value>
        - name: CI
          value: '1'
        - name: IN_DOCKER
          value: '1'
      command:
        - '/bin/bash'
      args:
        - '-c'
        - 'cd .. && binzx/otomi apply'
