{{ $v := .Values }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "maintenance.fullname" . }}
  namespace: maintenance
  labels: {{- include "maintenance.labels" . | nindent 4 }}
spec:
  schedule: "{{ $v.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: otomi/tools:{{ $v.toolsVersion }}
              name: {{ .Chart.Name }}
              resources: {{- $v.resources | toYaml | nindent 16 }}
              command: ["bash", "-c"]
              args:
                - |
                  ns="{{ $v.namespace }}"
                  labels="{{ $v.labels }}"
                  echo "MAINTENANCE TASK: deleting first found pod with labels $labels in namespace $ns"
                  echo "MAINTENANCE NOTE: this is needed because the component in question does not function correctly and loses desired state."
                  echo "MAINTENANCE TODO: find out if and why this is the case and keep filing reports for component with labels $labels in namespace $ns"
                  pod=$(kubectl -n $ns get po -l "$labels" -ojsonpath='{.items[0].metadata.name}')
                  kubectl -n $ns delete po $pod 
          restartPolicy: Never
