{{- $v := .Values }}
{{- if $v.apps.tekton.enabled }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  workspaces:
  - name: shared-data
  - name: harbor-pullsecret
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-revision)
  - name: build-push
    runAfter: 
    - fetch-source
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: harbor-pushsecret
    params:
    - name: DOCKERFILE
      value: $(params.dockerfile-path)
    - name: IMAGE
      value: $(params.image-reference)
---
{{- range $v.builds }}
{{- if eq .mode.type "docker" }}
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: docker-build-{{ .name }}-
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  pipelineRef:
    name: docker-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: harbor-pushsecret
    secret:
      secretName: harbor-pushsecret
  params:
  - name: repo-url
    value: {{ .mode.docker.repoUrl }}
  - name: dockerfile-path
    value: {{ .mode.docker.path }}    
  - name: image-reference
    value: harbor.{{ $v.cluster.domainSuffix }}/team-{{ $v.teamId }}/{{ .name }}:{{ .tag }}
{{- end }}
{{- end }}
{{- end }}