kind: pipeline
type: kubernetes
name: default

workspace:
  path: /home/app/stack/env

trigger:
  branch:
    - master
  event:
    - push

env:
  IN_DOCKER: '1'

steps:
  - name: slack-start
    image: plugins/slack
    environment:
      CLUSTER: __CLUSTER
      CLOUD: __CLOUD
    settings:
      webhook: __WEBHOOK
      channel: mon-otomi
      username: Drone
      template: >
        Started syncing cluster '__CLOUD-__CLUSTER' for customer '__CUSTOMER'...

  - name: decrypt
    image: eu.gcr.io/otomi-cloud/otomi-stack:__IMAGE_TAG
    environment:
      CLUSTER: __CLUSTER
      CLOUD: __CLOUD
      GCLOUD_SERVICE_KEY:
        from_secret: GCLOUD_SERVICE_KEY
    # The workspace is mounted as docker volume and is owned by root. See: https://discourse.drone.io/t/cant-run-tests-permissions-denied/4682/2
    user: 0
    commands:
      - chmod -R a+w env
      - cd .. && bin/crypt.sh decrypt

  - name: test
    image: eu.gcr.io/otomi-cloud/otomi-stack:__IMAGE_TAG
    environment:
      CLUSTER: __CLUSTER
      CLOUD: __CLOUD
    depends_on:
      - decrypt
    commands:
      - cd .. && bin/test.sh

  - name: deploy
    image: eu.gcr.io/otomi-cloud/otomi-stack:__IMAGE_TAG
    environment:
      CLUSTER: __CLUSTER
      CLOUD: __CLOUD
    commands:
      - cd .. && bin/otomi deploy
    depends_on:
      - test

  - name: slack-__CUSTOMER
    image: plugins/slack
    environment:
      CLUSTER: __CLUSTER
      CLOUD: __CLOUD
    depends_on:
      - deploy
    settings:
      webhook: __WEBHOOK
      channel: mon-otomi
      username: Drone
      template: >
        {{#success build.status}}
          Completed syncing cluster '__CLOUD-__CLUSTER' for customer '__CUSTOMER' :)
        {{else}}
          Failed syncing cluster '__CLOUD-__CLUSTER' for customer '__CUSTOMER' ;( Please take a look.
        {{/success}}
    when:
      status:
        - success
        - failure
