name: CloudTTY Build and Versioning

on:
  push:
    branches:
      - 'ani/feat/cloudshell'

env:
  CACHE_REGISTRY: ghcr.io
  CACHE_REPO: redkubes/otomi-tty
  REPO: otomi/cloudtty
  GIT_USER: redkubesbot

jobs:
  build-and-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine version
        id: determine-version
        run: |
          # if git log --format=%B -n 1  | grep -q "\[MAJOR\]"; then
          #   # If a "[MAJOR]" commit is found, increment the major version
          #   echo "VERSION=$(git describe --abbrev=0 --tags | awk -F. -v OFS=. '{$1 = $1 + 1; $2 = 0; $3 = 0} {print $0} || echo no major change')"
          # else
          # if git log --format=%B -n 1 ${{ github.sha }} | grep -q "\[MINOR\]"; then
          #     # If a "[MINOR]" commit is found, increment the minor version
          #     echo "VERSION=$(git describe --abbrev=0 --tags | awk -F. -v OFS=. '{$2 = $2 + 1; $3 = 0} {print $0}|| echo no minor change')"
          #   else
          #     # No special tag found, increment the patch version
          #     echo "VERSION=$(git describe --abbrev=0 --tags | awk -F. -v OFS=. '{$3 = $3 + 1} {print $0}')"
          #   fi
          # fi
          echo "VERSION='0.1.0'" >> $GITHUB_ENV
      - name: Build and tag Docker image
        run: |
          docker build -t $REPO -f tools/Dockerfile-tty .
          docker tag $REPO $REPO:${{ env.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.CACHE_REGISTRY }}
          username: ${{ env.GIT_USER }}
          password: '${{ secrets.NPM_TOKEN }}'

      - name: Push Docker image
        run: |
          docker push $REPO:${{ env.VERSION }}
          docker push $REPO:latest
